<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

/** @var Magento\Backend\Block\Template $block */

use Goomento\PageBuilder\ViewModel\PageContent;

/** @var PageContent $viewModel */
$viewModel = $block->getViewModel();

if ($viewModel->getContent()) :
    $contentId = $viewModel->getContent()->getId();
    ?>
    <div class="how-to-use">
        <h2><?= __('How to use') ?></h2>
        <ul class="">
            <li>1. <span><?= __('Add Widget with name "Page Builder Content" and set "Page" for it.') ?></span></li>
            <li>2.
                <span><?= __('CMS Page/Static Block') ?></span><code>{{block class="PageBuilderRenderer" content_id="<?= $contentId ?>"}}</code>
                <p><?= __('You can paste the above block of snippet into any page in Magento 2 and set %1 for it.', 'content_id') ?></p>
            </li>
            <li>
                <span><?= __('Template .phtml file') ?></span><code>&lt;?= $block-&gt;getLayout()-&gt;getBlock('pagebuilder.content.renderer')-&gt;setContentId(<?= $contentId ?>)-&gt;toHtml();?&gt;</code>
                <p><?= __('Open a .phtml file and insert where you want to display Page Builder Content.') ?></p>
            </li>
        </ul>
    </div>

    <style>
        .how-to-use { border: 2px dashed #333; padding: 25px; background: #ebffec; }
        .how-to-use h2 { font-weight: bold; }
        .how-to-use ul { list-style: none; }
        .how-to-use code { background: #009688; color: #fff; margin: 5px; padding: 1px 6px; border-radius: 4px; }
    </style>
<?php endif; ?>
