<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);
/**
 * @var $block Version
 */

use Goomento\PageBuilder\Configuration;
use Goomento\PageBuilder\Model\Config\Frontend\Version;

?>

<div>
    <div style="padding-left: 33%;">
        <p>Thanks for using <span style="font-weight: bold; color: #448940;">Goomento PageBuilder</span></p>
        <p>Module Version: <span style="background: #009499; color: #fff; padding: 1px 5px; border-radius: 3px;"><?= $block->getPageBuilderVersion() ?></span></p>
        <p>Editor Version: <span style="background: #009499; color: #fff; padding: 1px 5px; border-radius: 3px;"><?= Configuration::VERSION ?></span></p>
        <a target="_blank"
           href="https://github.com/Goomento/PageBuilder">
            <?= __('What\'s new?') ?>
        </a>
    </div>
</div>
