<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);
/**
 * @var $block Version
 */

use Goomento\PageBuilder\Developer;
use Goomento\PageBuilder\Model\Config\Frontend\Version;

?>

<div class="gmt-system_config" id="goomento_pagebuilder">
    <div class="gmt-system_config-wrapper">
        <p>Thanks for using <strong>Goomento</strong> - The Magento Page Builder Extension</p>
        <p>Module Version: <span class="gmt-version"><?= $block->escapeHtml(Developer::version()) ?></span></p>
        <a target="_blank"
           href="https://github.com/Goomento/PageBuilder">
            <?= $block->escapeHtml(__('What\'s new?')) ?>
        </a>
        <br />
        <a target="_blank"
           href="https://github.com/Goomento/PageBuilder/wiki">
            <?= $block->escapeHtml(__('Documents')) ?>
        </a>
        <div class="gmt-system_config-release-notes">
            <div class="gmt-system_config-release-note" style="display: none">
                <strong><?= $block->escapeHtml(__('Latest Release:')) ?></strong>
                <div>
                    <span><?= $block->escapeHtml(__('Version')) ?></span>
                    <span class="gmt-version"></span>
                </div>
                <div>
                    <span><?= $block->escapeHtml(__('Release Note')) ?></span>
                    <br>
                    <span class="gmt-version-note"></span>
                </div>
                <div>
                    <a href="#"><?= $block->escapeHtml(__('Download now')) ?></a>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .gmt-system_config .gmt-system_config-wrapper {padding-left: 33%;}
    .gmt-system_config .gmt-system_config-wrapper .gmt-version{background: #009499; color: #fff; padding: 1px 5px; border-radius: 3px;}
    .gmt-system_config .gmt-system_config-wrapper .gmt-system_config-release-note{padding: 10px; border: 1px solid #009499; max-width: 500px; border-radius: 5px; margin-top: 10px; margin-bottom: 10px; box-shadow: 2px 2px 2px 2px #e5e5e5;}
</style>
<script>
    require(['ko', 'jquery'], function (ko, $) {
        let json = localStorage.getItem('pagebuilder_releases'),
            time = parseInt(localStorage.getItem('pagebuilder_time')),
            aDayTime = 1000*60*60*24,
            nowTime = (new Date).getTime(),
            render = function (json) {
                let $root = $('#goomento_pagebuilder .gmt-system_config-release-note');
                $root.find('.gmt-version').text(json.tag_name);
                $root.find('.gmt-version-note').text(json.body);
                $root.find('a').attr('href', json.zipball_url);
                $root.show();
            },
            isValid = false;

        if (json && time && !isNaN(time)) {
            try {
                json = JSON.parse(json);
                if (nowTime - time > 0 && nowTime - time < aDayTime) {
                    isValid = true;
                }
            } catch (e) {}
        }

        if (isValid === true) {
            render(json);
        } else {
            $.get('https://api.github.com/repos/Goomento/PageBuilder/releases/latest', 'json')
                .done(function (jsonData) {
                    if (!jsonData || Object.keys(jsonData || {}).length < 1) {
                        return;
                    }
                    localStorage.setItem('pagebuilder_releases', JSON.stringify(jsonData));
                    localStorage.setItem('pagebuilder_time', nowTime);
                    render(jsonData);
                });
        }
    });
</script>
