<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);
/**
 * @var Template $block
 */

use Goomento\PageBuilder\Builder\Controls\Groups\TypographyGroup;
use Goomento\PageBuilder\Helper\Fonts;
use Goomento\PageBuilder\Helper\ObjectManagerHelper;
use Magento\Backend\Block\Template;

?>

<script type="text/template" id="tmpl-gmt-wysiwyg-editor-config">
    <div id="goomentoEditor-wrap" class="gmt-editor-wrap tmce-active">
        <div id="goomentoEditor-editor-tools" class="gmt-editor-tools hide-if-no-js">
            <div id="goomentoEditor-media-buttons" class="gmt-media-buttons">
                <button type="button" id="insert-media-button" class="gmt-button gmt-button-default insert-media add_media" data-editor="goomentoEditor">
                    <i class="fas fa-picture-o" aria-hidden="true"></i>
                    <?= $block->escapeHtml(__('Add Media')) ?>
                </button>
            </div>
        </div>
        <div id="goomentoEditor-editor-container" class="gmt-editor-container">
            <div id="qt_goomentoEditor_toolbar" class="quicktags-toolbar"></div>
            <textarea class="gmt-editor gmt-editor-area" autocomplete="off" cols="40" name="goomentoEditor" id="goomentoEditor">%%EDITORCONTENT%%</textarea>
        </div>
    </div>
</script>

<script type="text/template" id="tmpl-gmt-empty-preview">
    <div class="gmt-first-add">
        <div class="gmt-icon fa fa-plus"></div>
    </div>
</script>

<script type="text/template" id="tmpl-gmt-preview">
    <div class="gmt-section-wrap"></div>
</script>

<script type="text/template" id="tmpl-gmt-add-section">
    <# var ctrlLabel = goomento.env.mac ? '⌘' : 'Ctrl'; #>
    <div class="gmt-add-section-inner">
        <div class="gmt-add-section-close">
            <i class="fas fa-times" aria-hidden="true"></i>
            <span class="gmt-screen-only"><?= $block->escapeHtml(__('Close')); ?></span>
        </div>
        <div class="gmt-add-new-section">
            <div class="gmt-add-section-drag-title"><?= $block->escapeHtml(__('Drop widget here')); ?></div>
            <div class="gmt-add-section-area-helper">
                <span class="gmt-add-section-area-button gmt-add-section-button" title="<?= $block->escapeHtml(__('Add New Section')); ?>">
                    <i class="fas fa-plus"></i>
                </span>
                <span><?= $block->escapeHtml(__('Add new section')); ?></span>
            </div>
            <div class="gmt-add-section-area-helper">
                <span class="gmt-add-section-area-button gmt-add-template-button" title="<?= $block->escapeHtml(__('Add Template')); ?>">
                    <i class="fas fa-folder"></i>
                </span>
                <span><?= $block->escapeHtml(__('Add saved templates')); ?> ({{{ ctrlLabel }}} + Shift + L)</span>
            </div>
            <div class="gmt-add-section-area-helper">
                <span class="gmt-add-section-area-button gmt-shortcut-button" title="<?= $block->escapeHtml(__('All keyboard shortcuts')); ?>">
                    <i class="fas fa-question"></i>
                </span>
                <span><?= $block->escapeHtml(__('All keyboard shortcuts')); ?> ({{{ ctrlLabel }}} + ?)</span>
            </div>
        </div>
        <div class="gmt-select-preset">
            <div class="gmt-select-preset-title"><?= $block->escapeHtml(__('Select your Structure')); ?></div>
            <ul class="gmt-select-preset-list">
                <#
                var structures = [ 10, 20, 30, 40, 21, 22, 31, 32, 33, 50, 60, 34 ];

                _.each( structures, function( structure ) {
                var preset = goomento.presetsFactory.getPresetByStructure( structure ); #>

                <li class="gmt-preset gmt-column gmt-col-16" data-structure="{{ structure }}">
                    {{{ goomento.presetsFactory.getPresetSVG( preset.preset ).outerHTML }}}
                </li>
                <# } ); #>
            </ul>
        </div>
    </div>
</script>

<script type="text/template" id="tmpl-gmt-tag-controls-stack-empty">
    <?= $block->escapeHtml(__('This tag has no settings.')); ?>
</script>


<script type="text/template" id="tmpl-gmt-panel">
    <div id="gmt-panel-header-wrapper" class="tooltip-target" data-tooltip-gravity="n" data-tooltip="<?= $block->escapeHtml(__('Drag panel')) ?>">
        <i class="fas fa-ellipsis-h"></i>
    </div>
    <div id="gmt-panel-content-wrapper"></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-menu">
    <div id="gmt-panel-page-menu-content"></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-menu-group">
    <div class="gmt-panel-menu-group-title">{{{ title }}}</div>
    <div class="gmt-panel-menu-items"></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-menu-item">
    <div class="gmt-panel-menu-item-icon">
        <i class="{{ icon }}"></i>
    </div>
    <# if ( 'undefined' === typeof type || 'link' !== type ) { #>
    <div class="gmt-panel-menu-item-title">{{{ title }}}</div>
    <# } else {
    let target = ( 'undefined' !== typeof newTab && newTab ) ? '_blank' : '_self';
    #>
    <a href="{{ link }}" target="{{ target }}"><div class="gmt-panel-menu-item-title">{{{ title }}}</div></a>
    <# } #>
</script>

<script type="text/template" id="tmpl-gmt-panel-header">
    <div id="gmt-panel-header-menu-button" class="gmt-header-button">
        <i class="gmt-icon fa fa-bars tooltip-target" aria-hidden="true" data-tooltip="<?= $block->escapeHtml(__('Menu')); ?>"></i>
        <span class="gmt-screen-only"><?= $block->escapeHtml(__('Menu')); ?></span>
    </div>
    <div id="gmt-panel-header-title"></div>
    <div id="gmt-panel-header-add-button" class="gmt-header-button">
        <i class="gmt-icon goomento-logo-white tooltip-target" aria-hidden="true"
           data-tooltip="<?= $block->escapeHtml(__('Widgets Panel')); ?>"></i>
        <span class="gmt-screen-only"><?= $block->escapeHtml(__('Widgets Panel')); ?></span>
    </div>
</script>

<script type="text/template" id="tmpl-gmt-panel-controls-content">
    <# var ctrlLabel = goomento.env.mac ? '⌘' : 'Ctrl'; #>
    <div class="gmt-panel-control-tools gmt-panel-control-tools-start">
        <div id="gmt-panel-control-panel" class="gmt-panel-control-tool gmt-leave-open tooltip-target active"
             data-tooltip="<?= $block->escapeHtml(__('Widget List')); ?> ({{{ctrlLabel}}} + Shift + P)">
            <i class="fas fa-th-large" aria-hidden="true"></i>
        </div>
        <div id="gmt-panel-control-editing" class="gmt-panel-control-tool gmt-leave-open tooltip-target active"
             data-tooltip="<?= $block->escapeHtml(__('Toggle View')); ?> ({{{ctrlLabel}}} + P)">
            <i class="far fa-edit"></i>
        </div>
    </div>
    <div class="gmt-panel-control-tools gmt-panel-control-tools-center">
        <div class="gmt-panel-control-tool gmt-logo-brand">
            <i class="goomento-logo-white"></i>
        </div>
        <div id="gmt-panel-control-settings" class="gmt-panel-control-tool gmt-leave-open tooltip-target"
             data-tooltip="<?= $block->escapeHtml(__('Page Settings')); ?>">
            <i class="fas fa-cog" aria-hidden="true"></i>
        </div>
        <div id="gmt-panel-control-navigator" class="gmt-panel-control-tool tooltip-target"
             data-tooltip="<?= $block->escapeHtml(__('Navigator')) ?> ({{{ctrlLabel}}} + I)">
            <i class="fas fa-location-arrow" aria-hidden="true"></i>
        </div>
        <div id="gmt-panel-control-history" class="gmt-panel-control-tool gmt-leave-open tooltip-target"
             data-tooltip="<?= $block->escapeHtml(__('History')); ?> ({{{ctrlLabel}}} + Shift + H)">
            <i class="fas fa-history" aria-hidden="true"></i>
        </div>
        <div id="gmt-panel-control-revision" class="gmt-panel-control-tool gmt-leave-open tooltip-target"
             data-tooltip="<?= $block->escapeHtml(__('Saved draft')); ?> ({{{ctrlLabel}}} + H)">
            <i class="fas fa-code-branch" aria-hidden="true"></i>
        </div>
        <div id="gmt-panel-control-responsive" class="gmt-panel-control-wrapper gmt-panel-control-tool">
            <div class="gmt-panel-control-responsive-devices gmt-panel-control-group">
                <div class="gmt-panel-control-responsive-device tooltip-target gmt-panel-control-tool"
                     data-device-mode="desktop" data-tooltip="<?= $block->escapeHtml(__('Desktop')); ?> ({{{ctrlLabel}}} + Shift + M)">
                    <i class="gmt-icon fa fa-desktop" aria-hidden="true"></i>
                </div>
                <div class="gmt-panel-control-responsive-device tooltip-target gmt-panel-control-tool"
                     data-device-mode="tablet" data-tooltip="<?= $block->escapeHtml(__('Tablet')); ?> ({{{ctrlLabel}}} + Shift + M)">
                    <i class="gmt-icon fa fa-tablet" aria-hidden="true"></i>
                </div>
                <div class="gmt-panel-control-responsive-device tooltip-target gmt-panel-control-tool"
                     data-device-mode="mobile" data-tooltip="<?= $block->escapeHtml(__('Mobile')); ?> ({{{ctrlLabel}}} + Shift + M)">
                    <i class="gmt-icon fa fa-mobile" aria-hidden="true"></i>
                </div>
            </div>
        </div>
        <div id="gmt-panel-control-saver-preview" class="gmt-panel-control-tool tooltip-target"
             data-tooltip="<?= $block->escapeHtml(__('Preview Changes')); ?>">
        <span id="gmt-panel-control-saver-preview-label">
            <i class="fas fa-eye" aria-hidden="true"></i>
            <span class="gmt-screen-only"><?= $block->escapeHtml(__('Preview Changes')); ?></span>
        </span>
        </div>
        <div id="gmt-panel-control-saver-publish" class="gmt-panel-control-tool">
            <button id="gmt-panel-saver-button-publish" class="gmt-button gmt-button-success gmt-disabled tooltip-target"
                    data-tooltip="<?= $block->escapeHtml(__('Saved')); ?> ({{{ctrlLabel}}} + S)">
            <span class="gmt-state-icon">
                <i class="fa-circle-notch fas spinning" aria-hidden="true"></i>
            </span>
                <span id="gmt-panel-saver-button-publish-label">
                <?= $block->escapeHtml(__('Saved')); ?>
            </span>
            </button>
            <div id="gmt-panel-control-saver-options" class="gmt-panel-control-tool gmt-toggle-state">
                <button id="gmt-panel-saver-button-save-options" class="gmt-button gmt-button-success tooltip-target gmt-disabled"
                        data-tooltip="<?= $block->escapeHtml(__('Save Options')); ?>">
                    <i class="fas fa-caret-up" aria-hidden="true"></i>
                    <span class="gmt-screen-only"><?= $block->escapeHtml(__('Save Options')); ?></span>
                </button>
                <div class="gmt-panel-control-sub-menu-wrapper">
                    <p class="gmt-last-edited-wrapper">
                <span class="gmt-state-icon">
                    <i class="fa-circle-notch fas spinning" aria-hidden="true"></i>
                </span>
                        <span class="gmt-last-edited">
                    {{{ goomento.config.document.last_edited }}}
                </span>
                    </p>
                    <div class="gmt-panel-control-sub-menu">
                        <div id="gmt-panel-control-sub-menu-item-save-template" class="gmt-panel-control-sub-menu-item">
                            <i class="gmt-icon fa fa-folder" aria-hidden="true"></i>
                            <span class="gmt-title"><?= $block->escapeHtml(__('Save as Template')); ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="gmt-panel-control-tools gmt-panel-control-tools-end">
        <div id="gmt-panel-control-general-settings" class="gmt-panel-control-tool gmt-leave-open tooltip-target"
             data-tooltip="<?= $block->escapeHtml(__('Global Settings')); ?>">
            <i class="fas fa-cogs" aria-hidden="true"></i>
        </div>
        <div id="gmt-panel-control-help" onclick="$e.run('tour/start')" class="gmt-panel-control-tool gmt-leave-open tooltip-target"
             data-tooltip="<?= $block->escapeHtml(__('How To Use?')); ?>">
            <i class="fas fa-info-circle"></i>
        </div>
        <div id="gmt-panel-control-back-to-dashboard" class="gmt-panel-control-tool gmt-leave-open tooltip-target"
             data-tooltip="<?= $block->escapeHtml(__('Back To Magento')); ?>">
            <i class="fas fa-sign-out-alt" aria-hidden="true"></i>
        </div>
    </div>
</script>

<script type="text/template" id="tmpl-editor-content">
    <div class="gmt-panel-navigation">
        <div class="gmt-component-tab gmt-panel-navigation-tab gmt-tab-control-close tooltip-target"
             data-tooltip-gravity="n" data-tooltip="<?= $block->escapeHtml(__('Close')) ?>" data-tab="close">
            <a href="#"><?= $block->escapeHtml(__('Close')) ?></a>
        </div>
        <# _.each( elementData.tabs_controls, function( tabTitle, tabSlug ) {
        if ( 'content' !== tabSlug && ! goomento.userCan( 'save' ) ) {
        return;
        }
        $e.bc.ensureTab( 'panel/editor', tabSlug );
        #>
        <div class="gmt-component-tab gmt-panel-navigation-tab gmt-tab-control-{{ tabSlug }} tooltip-target"
             data-tooltip-gravity="n" data-tooltip="{{{ tabTitle }}}" data-tab="{{ tabSlug }}">
            <a href="#">{{{ tabTitle }}}</a>
        </div>
        <# } ); #>
    </div>
    <# if ( elementData.reload_preview ) { #>
    <div class="gmt-update-preview">
        <div class="gmt-update-preview-title"><?= $block->escapeHtml(__('Update changes to page')); ?></div>
        <div class="gmt-update-preview-button-wrapper">
            <button class="gmt-update-preview-button gmt-button gmt-button-success"><?= $block->escapeHtml(__('Apply')); ?></button>
        </div>
    </div>
    <# } #>
    <div id="gmt-controls"></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-schemes-disabled">
    <i class="gmt-nerd-box-icon fas fa-glasses" aria-hidden="true"></i>
    <div class="gmt-nerd-box-title">{{{ '<?= $block->escapeHtmlAttr(__("%s are disabled")); ?>'.replace( '%s', disabledTitle ) }}}</div>
    <div class="gmt-nerd-box-message">You can enable it from the <a href="%s" target="_blank">Goomento settings page.</a></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-scheme-color-item">
    <div class="gmt-panel-scheme-color-input-wrapper">
        <input type="text" class="gmt-panel-scheme-color-value" value="{{ value }}" data-alpha="true" />
    </div>
    <div class="gmt-panel-scheme-color-title">{{{ title }}}</div>
</script>

<script type="text/template" id="tmpl-gmt-panel-scheme-typography-item">
    <div class="gmt-panel-heading">
        <div class="gmt-panel-heading-toggle">
            <i class="gmt-icon" aria-hidden="true"></i>
        </div>
        <div class="gmt-panel-heading-title">{{{ title }}}</div>
    </div>
    <div class="gmt-panel-scheme-typography-items gmt-panel-box-content">
        <?php
        $schemeFieldsKeys = TypographyGroup::getSchemeFieldsKeys();

        $typographyGroup = ObjectManagerHelper::getControlsManager()
            ->getControlGroups(TypographyGroup::NAME);

        $typographyFields = $typographyGroup->getFields();

        $schemeFields = array_intersect_key($typographyFields, array_flip($schemeFieldsKeys));

        foreach ($schemeFields as $optionName => $option):
            ?>
            <div class="gmt-panel-scheme-typography-item">
                <div class="gmt-panel-scheme-item-title gmt-control-title"><?=  /** @noEscape */ $option['label']; ?></div>
                <div class="gmt-panel-scheme-typography-item-value">
                    <?php if ('select' === $option['type']): ?>
                        <select name="<?= $block->escapeHtml($optionName); ?>" class="gmt-panel-scheme-typography-item-field">
                            <?php foreach ($option['options'] as $fieldKey => $fieldValue): ?>
                                <option value="<?= $block->escapeHtml($fieldKey); ?>"><?=  /** @noEscape */ $fieldValue; ?></option>
                            <?php endforeach; ?>
                        </select>
                    <?php elseif ('font' === $option['type']): ?>
                        <select name="<?= $block->escapeHtml($optionName); ?>" class="gmt-panel-scheme-typography-item-field">
                            <option value=""><?= $block->escapeHtml(__('Default')); ?></option>
                            <?php foreach (Fonts::getFontGroups() as $groupType => $groupLabel): ?>
                                <optgroup label="<?= $block->escapeHtml($groupLabel); ?>">
                                    <?php foreach (Fonts::getFontsByGroups([ $groupType ]) as $fontTitle => $fontType): ?>
                                        <option value="<?= $block->escapeHtml($fontTitle); ?>"><?=  /** @noEscape */ $fontTitle; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            <?php endforeach; ?>
                        </select>
                    <?php elseif ('text' === $option['type']): ?>
                        <input name="<?= $block->escapeHtml($optionName); ?>" class="gmt-panel-scheme-typography-item-field" />
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</script>

<script type="text/template" id="tmpl-gmt-control-responsive-switchers">
    <div class="gmt-control-responsive-switchers">
        <#
        var devices = responsive.devices || [ 'desktop', 'tablet', 'mobile' ];

        _.each( devices, function( device ) { #>
        <a class="gmt-responsive-switcher gmt-responsive-switcher-{{ device }}" data-device="{{ device }}">
            <i class="fas fa-{{ device }}"></i>
        </a>
        <# } );
        #>
    </div>
</script>

<script type="text/template" id="tmpl-gmt-control-dynamic-switcher">
    <div class="gmt-control-dynamic-switcher-wrapper">
        <div class="gmt-control-dynamic-switcher tooltip-target" data-tooltip="<?= $block->escapeHtml(__('Dynamic value')) ?>">
            <i class="fas fa-bolt"></i>
        </div>
    </div>
</script>

<script type="text/template" id="tmpl-gmt-control-dynamic-cover">
    <div class="gmt-dynamic-cover__settings">
        <i class="fas fa-{{ hasSettings ? 'wrench' : 'database' }}"></i>
    </div>
    <div class="gmt-dynamic-cover__title" title="{{{ title + ' ' + content }}}">{{{ title + ' ' + content }}}</div>
    <# if ( isRemovable ) { #>
    <div class="gmt-dynamic-cover__remove">
        <i class="fas fa-times-circle"></i>
    </div>
    <# } #>
</script>

<script type="text/template" id="tmpl-gmt-repeater-row">
    <div class="gmt-repeater-row-tools <# if ( itemActions.sort )  {  #> tooltip-target <# } #>"
    <# if ( itemActions.sort ) {  #> data-tooltip="<?= $block->escapeHtml(__('Drag me')); ?>" <# } #>>
    <div class="gmt-repeater-row-item-title"></div>
    <# if ( itemActions.duplicate ) {  #>
    <div class="gmt-repeater-row-tool gmt-repeater-tool-duplicate tooltip-target" data-tooltip="<?= $block->escapeHtml(__('Duplicate')); ?>">
        <i class="far fa-copy"></i>
        <span class="gmt-screen-only"><?= $block->escapeHtml(__('Duplicate')); ?></span>
    </div>
    <# }
    if ( itemActions.remove ) {  #>
    <div class="gmt-repeater-row-tool gmt-repeater-tool-remove tooltip-target" data-tooltip="<?= $block->escapeHtml(__('Remove')); ?>">
        <i class="fas fa-times" aria-hidden="true"></i>
        <span class="gmt-screen-only"><?= $block->escapeHtml(__('Remove')); ?></span>
    </div>
    <# } #>
    </div>
    <div class="gmt-repeater-row-controls"></div>
</script>

