<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 */
?>

<script type="text/template" id="tmpl-gmt-panel-history-page">
    <div id="gmt-history-list"></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-history-no-items">
    <i class="gmt-nerd-box-icon fas fa-glasses"></i>
    <div class="gmt-nerd-box-title"><?= $block->escapeHtml(__('No History Yet')); ?></div>
    <div class="gmt-nerd-box-message"><?= $block->escapeHtml(__('Once you start working, you\'ll be able to redo / undo any action you make in the editor.')); ?></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-history-item">
    <div class="gmt-history-item__details">
        <span class="gmt-history-item__title">{{{ title }}}</span>
        <span class="gmt-history-item__subtitle">{{{ subTitle }}}</span>
        <span class="gmt-history-item__action">{{{ action }}}</span>
    </div>
    <div class="gmt-history-item__icon">
        <span class="gmt-icon" aria-hidden="true"></span>
    </div>
</script>
