<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);
?>
<script type="text/template" id="tmpl-gmt-hotkeys">
	<# var ctrlLabel = environment.mac ? '⌘' : 'Ctrl'; #>
	<div id="gmt-hotkeys__content">
		<div id="gmt-hotkeys__actions" class="gmt-hotkeys__col">

			<div class="gmt-hotkeys__header">
				<h3><?= __( 'Actions' ); ?></h3>
			</div>
			<div class="gmt-hotkeys__list">
				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Undo' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>{{{ ctrlLabel }}}</span>
						<span>Z</span>
					</div>
				</div>

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Redo' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>{{{ ctrlLabel }}}</span>
						<span>Shift</span>
						<span>Z</span>
					</div>
				</div>

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Copy' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>{{{ ctrlLabel }}}</span>
						<span>C</span>
					</div>
				</div>

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Paste' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>{{{ ctrlLabel }}}</span>
						<span>V</span>
					</div>
				</div>

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Paste Style' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>{{{ ctrlLabel }}}</span>
						<span>Shift</span>
						<span>V</span>
					</div>
				</div>

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Delete' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>Delete</span>
					</div>
				</div>

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Duplicate' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>{{{ ctrlLabel }}}</span>
						<span>D</span>
					</div>
				</div>

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Save' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>{{{ ctrlLabel }}}</span>
						<span>S</span>
					</div>
				</div>

			</div>
		</div>

		<div id="gmt-hotkeys__navigation" class="gmt-hotkeys__col">

			<div class="gmt-hotkeys__header">
				<h3><?= __( 'Go To' ); ?></h3>
			</div>
			<div class="gmt-hotkeys__list">

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Show / Hide Panel' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>{{{ ctrlLabel }}}</span>
						<span>P</span>
					</div>
				</div>

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Responsive Mode' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>{{{ ctrlLabel }}}</span>
						<span>Shift</span>
						<span>M</span>
					</div>
				</div>

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'History' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>{{{ ctrlLabel }}}</span>
						<span>Shift</span>
						<span>H</span>
					</div>
				</div>

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Navigator' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>{{{ ctrlLabel }}}</span>
						<span>I</span>
					</div>
				</div>

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Template Library' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>{{{ ctrlLabel }}}</span>
						<span>Shift</span>
						<span>L</span>
					</div>
				</div>

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Keyboard Shortcuts' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>{{{ ctrlLabel }}}</span>
						<span>?</span>
					</div>
				</div>

				<div class="gmt-hotkeys__item">
					<div class="gmt-hotkeys__item--label"><?= __( 'Quit' ); ?></div>
					<div class="gmt-hotkeys__item--shortcut">
						<span>Esc</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</script>
