<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);
/**
 * @var Template $block
 */

use Goomento\PageBuilder\Helper\DataHelper;
use Magento\Backend\Block\Template;
use Goomento\PageBuilder\Helper\ObjectManagerHelper;
use Goomento\PageBuilder\Helper\UrlBuilderHelper;
use Magento\Framework\UrlInterface;

$editor = ObjectManagerHelper::getEditor();
$document = $editor->getDocument();
$storeIds = $editor->getBuildableContent()->getOriginContent()->getStoreIds();
$storeId = $mediaUrl = '';
if ($storeIds) {
    $storeId = implode(',', $storeIds);
} else {
    $storeId = '0';
}
if (DataHelper::getCustomMediaUrl()) {
    $mediaUrl = DataHelper::getCustomMediaUrl();
} else {
    $mediaUrl = UrlBuilderHelper::getFrontendUrl('', ['_type' => UrlInterface::URL_TYPE_MEDIA]);
}
?>
<div class="image-bucket" data-bind="scope: 'uploader'" style="height: 0;width: 0">
    <input type="hidden" id="image-bucket">
</div>
<script>
    window.mediaUrl = "<?=  /** @noEscape */ $mediaUrl ?>";
</script>
<script type="text/x-magento-init">
{
    ".image-bucket": {
        "Magento_Ui/js/core/app": {
                "components": {
                        "image-bucket": {
                            "component": "Goomento_PageBuilder/js/media-bucket/uploader",
                            "mediaGallery":{
                            "openDialogUrl":"<?= $block->escapeUrl($block->getUrl('cms/wysiwyg_images/index', ['_secure' => true])) ?>",
                            "initialOpenSubpath":"wysiwyg",
                            "storeId":"<?=  /** @noEscape */ $storeId ?>"
                    }
                }
            }
        }
    }
}
</script>
