<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Builder\Controls\Groups\TypographyGroup;
use Goomento\PageBuilder\Builder\Fonts;
use Goomento\PageBuilder\Helper\EscaperHelper;
use Goomento\PageBuilder\Helper\ObjectManagerHelper;

?>
<script type="text/template" id="tmpl-gmt-panel">
    <div id="gmt-panel-header-wrapper">
        <i class="fas fa-ellipsis-h"></i>
    </div>
    <div id="gmt-panel-content-wrapper"></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-menu">
    <div id="gmt-panel-page-menu-content"></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-menu-group">
    <div class="gmt-panel-menu-group-title">{{{ title }}}</div>
    <div class="gmt-panel-menu-items"></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-menu-item">
    <div class="gmt-panel-menu-item-icon">
        <i class="{{ icon }}"></i>
    </div>
    <# if ( 'undefined' === typeof type || 'link' !== type ) { #>
    <div class="gmt-panel-menu-item-title">{{{ title }}}</div>
    <# } else {
    let target = ( 'undefined' !== typeof newTab && newTab ) ? '_blank' : '_self';
    #>
    <a href="{{ link }}" target="{{ target }}"><div class="gmt-panel-menu-item-title">{{{ title }}}</div></a>
    <# } #>
</script>

<script type="text/template" id="tmpl-gmt-panel-header">
    <div id="gmt-panel-header-menu-button" class="gmt-header-button">
        <i class="gmt-icon fa fa-bars tooltip-target" aria-hidden="true" data-tooltip="<?= __('Menu'); ?>"></i>
        <span class="gmt-screen-only"><?= __( 'Menu' ); ?></span>
    </div>
    <div id="gmt-panel-header-title"></div>
    <div id="gmt-panel-header-add-button" class="gmt-header-button">
        <i class="gmt-icon goomento-logo-white tooltip-target" aria-hidden="true" data-tooltip="<?= __('Widgets Panel'); ?>"></i>
        <span class="gmt-screen-only"><?= __( 'Widgets Panel' ); ?></span>
    </div>
</script>

<script type="text/template" id="tmpl-gmt-panel-controls-content">
    <div class="gmt-panel-control-tools gmt-panel-control-tools-start">
        <div id="gmt-panel-control-panel" class="gmt-panel-control-tool gmt-leave-open tooltip-target active" data-tooltip="<?= __('Widget List'); ?>">
            <i class="fas fa-th-large" aria-hidden="true"></i>
        </div>
        <div id="gmt-panel-control-editing" class="gmt-panel-control-tool gmt-leave-open tooltip-target active" data-tooltip="<?= __('Toggle View'); ?>">
            <i class="far fa-edit"></i>
        </div>
    </div>
    <div class="gmt-panel-control-tools gmt-panel-control-tools-center">
        <div class="gmt-panel-control-tool gmt-logo-brand">
            <i class="goomento-logo-white"></i>
        </div>
        <div id="gmt-panel-control-settings" class="gmt-panel-control-tool gmt-leave-open tooltip-target" data-tooltip="<?= __('Page Settings'); ?>">
            <i class="fas fa-cog" aria-hidden="true"></i>
        </div>
        <div id="gmt-panel-control-navigator" class="gmt-panel-control-tool tooltip-target" data-tooltip="<?= __('Navigator') ?>">
            <i class="fas fa-location-arrow" aria-hidden="true"></i>
        </div>
        <div id="gmt-panel-control-history" class="gmt-panel-control-tool gmt-leave-open tooltip-target" data-tooltip="<?= __('History & Revision'); ?>">
            <i class="fas fa-history" aria-hidden="true"></i>
        </div>
        <div id="gmt-panel-control-responsive" class="gmt-panel-control-tool">
            <div class="gmt-panel-control-responsive-devices">
                <div class="gmt-panel-control-responsive-device tooltip-target" data-device-mode="desktop" data-tooltip="<?= __('Desktop'); ?>">
                    <i class="gmt-icon fa fa-desktop" aria-hidden="true"></i>
                </div>
                <div class="gmt-panel-control-responsive-device tooltip-target" data-device-mode="tablet" data-tooltip="<?= __('Tablet'); ?>">
                    <i class="gmt-icon fa fa-tablet" aria-hidden="true"></i>
                </div>
                <div class="gmt-panel-control-responsive-device tooltip-target" data-device-mode="mobile" data-tooltip="<?= __('Mobile'); ?>">
                    <i class="gmt-icon fa fa-mobile" aria-hidden="true"></i>
                </div>
            </div>
        </div>
        <div id="gmt-panel-control-saver-preview" class="gmt-panel-control-tool tooltip-target" data-tooltip="<?= __('Preview Changes'); ?>">
		<span id="gmt-panel-control-saver-preview-label">
			<i class="fas fa-eye" aria-hidden="true"></i>
			<span class="gmt-screen-only"><?= __( 'Preview Changes' ); ?></span>
		</span>
        </div>
        <div id="gmt-panel-control-saver-publish" class="gmt-panel-control-tool">
            <button id="gmt-panel-saver-button-publish" class="gmt-button gmt-button-success gmt-disabled tooltip-target" data-tooltip="<?= __('Saved'); ?>">
			<span class="gmt-state-icon">
				<i class="fa-circle-notch fas spinning" aria-hidden="true"></i>
			</span>
                <span id="gmt-panel-saver-button-publish-label">
				<?= __( 'Saved' ); ?>
			</span>
            </button>
            <div id="gmt-panel-control-saver-options" class="gmt-panel-control-tool gmt-toggle-state">
                <button id="gmt-panel-saver-button-save-options" class="gmt-button gmt-button-success tooltip-target gmt-disabled" data-tooltip="<?= __('Save Options'); ?>">
                    <i class="fas fa-caret-up" aria-hidden="true"></i>
                    <span class="gmt-screen-only"><?= __( 'Save Options' ); ?></span>
                </button>
                <div class="gmt-panel-control-sub-menu-wrapper">
                    <p class="gmt-last-edited-wrapper">
				<span class="gmt-state-icon">
					<i class="fa-circle-notch fas spinning" aria-hidden="true"></i>
				</span>
                        <span class="gmt-last-edited">
					{{{ goomento.config.document.last_edited }}}
				</span>
                    </p>
                    <div class="gmt-panel-control-sub-menu">
                        <div id="gmt-panel-control-sub-menu-item-save-template" class="gmt-panel-control-sub-menu-item">
                            <i class="gmt-icon fa fa-folder" aria-hidden="true"></i>
                            <span class="gmt-title"><?= __( 'Save as Template' ); ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="gmt-panel-control-tools gmt-panel-control-tools-end">
        <div id="gmt-panel-control-general-settings" class="gmt-panel-control-tool gmt-leave-open tooltip-target" data-tooltip="<?= __('Global Settings'); ?>">
            <i class="fas fa-cogs" aria-hidden="true"></i>
        </div>
        <div id="gmt-panel-control-back-to-dashboard" class="gmt-panel-control-tool gmt-leave-open tooltip-target" data-tooltip="<?= __('Back To Magento'); ?>">
            <i class="fab fa-magento" aria-hidden="true"></i>
        </div>
    </div>
</script>

<script type="text/template" id="tmpl-gmt-mode-switcher-content">
    <input id="gmt-mode-switcher-preview-input" type="checkbox">
    <label for="gmt-mode-switcher-preview-input" id="gmt-mode-switcher-preview" title="<?= __('Hide Panel'); ?>">
        <i class="gmt-icon" aria-hidden="true"></i>
        <span class="gmt-screen-only"><?= __( 'Hide Panel' ); ?></span>
    </label>
</script>

<script type="text/template" id="tmpl-editor-content">
    <div class="gmt-panel-navigation">
        <div class="gmt-component-tab gmt-panel-navigation-tab gmt-tab-control-close" data-tab="close">
            <a href="#"><?= __('Close') ?></a>
        </div>
        <# _.each( elementData.tabs_controls, function( tabTitle, tabSlug ) {
        if ( 'content' !== tabSlug && ! goomento.userCan( 'save' ) ) {
        return;
        }
        $e.bc.ensureTab( 'panel/editor', tabSlug );
        #>
        <div class="gmt-component-tab gmt-panel-navigation-tab gmt-tab-control-{{ tabSlug }}" data-tab="{{ tabSlug }}">
            <a href="#">{{{ tabTitle }}}</a>
        </div>
        <# } ); #>
    </div>
    <# if ( elementData.reload_preview ) { #>
    <div class="gmt-update-preview">
        <div class="gmt-update-preview-title"><?= __( 'Update changes to page' ); ?></div>
        <div class="gmt-update-preview-button-wrapper">
            <button class="gmt-update-preview-button gmt-button gmt-button-success"><?= __( 'Apply' ); ?></button>
        </div>
    </div>
    <# } #>
    <div id="gmt-controls"></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-schemes-disabled">
    <i class="gmt-nerd-box-icon fas fa-glasses" aria-hidden="true"></i>
    <div class="gmt-nerd-box-title">{{{ '<?= __( "%s are disabled" ); ?>'.replace( '%s', disabledTitle ) }}}</div>
    <div class="gmt-nerd-box-message">You can enable it from the <a href="%s" target="_blank">Goomento settings page.</a></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-scheme-color-item">
    <div class="gmt-panel-scheme-color-input-wrapper">
        <input type="text" class="gmt-panel-scheme-color-value" value="{{ value }}" data-alpha="true" />
    </div>
    <div class="gmt-panel-scheme-color-title">{{{ title }}}</div>
</script>

<script type="text/template" id="tmpl-gmt-panel-scheme-typography-item">
    <div class="gmt-panel-heading">
        <div class="gmt-panel-heading-toggle">
            <i class="gmt-icon" aria-hidden="true"></i>
        </div>
        <div class="gmt-panel-heading-title">{{{ title }}}</div>
    </div>
    <div class="gmt-panel-scheme-typography-items gmt-panel-box-content">
        <?php
        $schemeFieldsKeys = TypographyGroup::getSchemeFieldsKeys();

        $typographyGroup = ObjectManagerHelper::getControlsManager()
            ->getControlGroups( TypographyGroup::NAME );

        $typographyFields = $typographyGroup->getFields();

        $schemeFields = array_intersect_key( $typographyFields, array_flip( $schemeFieldsKeys ) );

        foreach ( $schemeFields as $optionName => $option ) :
            ?>
            <div class="gmt-panel-scheme-typography-item">
                <div class="gmt-panel-scheme-item-title gmt-control-title"><?= $option['label']; ?></div>
                <div class="gmt-panel-scheme-typography-item-value">
                    <?php if ( 'select' === $option['type'] ) : ?>
                        <select name="<?= EscaperHelper::escapeHtml($optionName); ?>" class="gmt-panel-scheme-typography-item-field">
                            <?php foreach ( $option['options'] as $fieldKey => $fieldValue ) : ?>
                                <option value="<?= EscaperHelper::escapeHtml($fieldKey); ?>"><?= $fieldValue; ?></option>
                            <?php endforeach; ?>
                        </select>
                    <?php elseif ( 'font' === $option['type'] ) : ?>
                        <select name="<?= EscaperHelper::escapeHtml($optionName); ?>" class="gmt-panel-scheme-typography-item-field">
                            <option value=""><?= __( 'Default' ); ?></option>
                            <?php foreach ( Fonts::getFontGroups() as $groupType => $groupLabel ) : ?>
                                <optgroup label="<?= EscaperHelper::escapeHtml($groupLabel); ?>">
                                    <?php foreach ( Fonts::getFontsByGroups( [ $groupType ] ) as $fontTitle => $fontType ) : ?>
                                        <option value="<?= EscaperHelper::escapeHtml($fontTitle); ?>"><?= $fontTitle; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            <?php endforeach; ?>
                        </select>
                    <?php elseif ( 'text' === $option['type'] ) : ?>
                        <input name="<?= EscaperHelper::escapeHtml($optionName); ?>" class="gmt-panel-scheme-typography-item-field" />
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</script>

<script type="text/template" id="tmpl-gmt-control-responsive-switchers">
    <div class="gmt-control-responsive-switchers">
        <#
        var devices = responsive.devices || [ 'desktop', 'tablet', 'mobile' ];

        _.each( devices, function( device ) { #>
        <a class="gmt-responsive-switcher gmt-responsive-switcher-{{ device }}" data-device="{{ device }}">
            <i class="fas fa-{{ device }}"></i>
        </a>
        <# } );
        #>
    </div>
</script>

<script type="text/template" id="tmpl-gmt-control-dynamic-switcher">
    <div class="gmt-control-dynamic-switcher-wrapper">
        <div class="gmt-control-dynamic-switcher">
            <i class="fa fa-ellipsis-h"></i>
        </div>
    </div>
</script>

<script type="text/template" id="tmpl-gmt-control-dynamic-cover">
    <div class="gmt-dynamic-cover__settings">
        <i class="fas fa-{{ hasSettings ? 'wrench' : 'database' }}"></i>
    </div>
    <div class="gmt-dynamic-cover__title" title="{{{ title + ' ' + content }}}">{{{ title + ' ' + content }}}</div>
    <# if ( isRemovable ) { #>
    <div class="gmt-dynamic-cover__remove">
        <i class="fas fa-times-circle"></i>
    </div>
    <# } #>
</script>
