<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Helper\ObjectManagerHelper;

$document = ObjectManagerHelper::getEditor()->getDocument();

?>
<script type="text/template" id="tmpl-gmt-template-library-header-actions">
    <#  if ( goomento.userCan( 'import' ) ) { #>
	<div id="gmt-template-library-header-import" class="gmt-templates-modal__header__item">
		<i class="fas fa-upload" aria-hidden="true" title="<?= __('Import Template'); ?>"></i>
		<span class="gmt-screen-only"><?= __( 'Import Template' ); ?></span>
	</div>
    <#  } #>
    <#  if ( goomento.userCan( 'view' ) ) { #>
	<div id="gmt-template-library-header-sync" class="gmt-templates-modal__header__item">
		<i class="fas fa-sync-alt" aria-hidden="true" title="<?= __('Sync Library'); ?>"></i>
		<span class="gmt-screen-only"><?= __( 'Sync Library' ); ?></span>
	</div>
    <#  } #>
    <#  if ( goomento.userCan( 'save' ) ) { #>
	<div id="gmt-template-library-header-save" class="gmt-templates-modal__header__item">
		<i class="far fa-save" aria-hidden="true" title="<?= __('Save'); ?>"></i>
		<span class="gmt-screen-only"><?= __( 'Save' ); ?></span>
	</div>
    <#  } #>
</script>

<script type="text/template" id="tmpl-gmt-template-library-header-menu">
	<# jQuery.each( tabs, ( tab, args ) => { #>
		<div class="gmt-component-tab gmt-template-library-menu-item" data-tab="{{{ tab }}}">{{{ args.title }}}</div>
	<# } ); #>
</script>

<script type="text/template" id="tmpl-gmt-template-library-header-preview">
	<div id="gmt-template-library-header-preview-insert-wrapper" class="gmt-templates-modal__header__item">
		{{{ goomento.templates.layout.getTemplateActionButton( obj ) }}}
	</div>
</script>

<script type="text/template" id="tmpl-gmt-template-library-header-back">
	<i class="eicon-" aria-hidden="true"></i>
	<span><?= __( 'Back to Library' ); ?></span>
</script>

<script type="text/template" id="tmpl-gmt-template-library-loading">
	<div class="gmt-loader-wrapper">
		<div class="gmt-loader">
			<div class="gmt-loader-boxes">
				<div class="gmt-loader-box"></div>
				<div class="gmt-loader-box"></div>
				<div class="gmt-loader-box"></div>
				<div class="gmt-loader-box"></div>
			</div>
		</div>
		<div class="gmt-loading-title"><?= __( 'Loading' ); ?></div>
	</div>
</script>

<script type="text/template" id="tmpl-gmt-template-library-templates">
	<#
		var activeSource = goomento.templates.getFilter('source');
	#>
	<div id="gmt-template-library-toolbar">
		<# if ( 'remote' === activeSource ) {
			var activeType = goomento.templates.getFilter('type');
			#>
			<div id="gmt-template-library-filter-toolbar-remote" class="gmt-template-library-filter-toolbar">
				<# if ( 'page' === activeType ) { #>
					<div id="gmt-template-library-order">
						<input type="radio" id="gmt-template-library-order-new" class="gmt-template-library-order-input" name="gmt-template-library-order" value="date">
						<label for="gmt-template-library-order-new" class="gmt-template-library-order-label"><?= __( 'New' ); ?></label>
						<input type="radio" id="gmt-template-library-order-trend" class="gmt-template-library-order-input" name="gmt-template-library-order" value="trendIndex">
						<label for="gmt-template-library-order-trend" class="gmt-template-library-order-label"><?= __( 'Trend' ); ?></label>
						<input type="radio" id="gmt-template-library-order-popular" class="gmt-template-library-order-input" name="gmt-template-library-order" value="popularityIndex">
						<label for="gmt-template-library-order-popular" class="gmt-template-library-order-label"><?= __( 'Popular' ); ?></label>
					</div>
				<# } else {
					var config = goomento.templates.getConfig( activeType );
					if ( config.categories ) { #>
						<div id="gmt-template-library-filter">
							<select id="gmt-template-library-filter-subtype" class="gmt-template-library-filter-select" data-gmt-filter="subtype">
								<option></option>
								<# config.categories.forEach( function( category ) {
									var selected = category === goomento.templates.getFilter( 'subtype' ) ? ' selected' : '';
									#>
									<option value="{{ category }}"{{{ selected }}}>{{{ category }}}</option>
								<# } ); #>
							</select>
						</div>
					<# }
				} #>
				<div id="gmt-template-library-my-favorites">
					<# var checked = goomento.templates.getFilter( 'favorite' ) ? ' checked' : ''; #>
					<input id="gmt-template-library-filter-my-favorites" type="checkbox"{{{ checked }}}>
					<label id="gmt-template-library-filter-my-favorites-label" for="gmt-template-library-filter-my-favorites">
						<i class="gmt-icon" aria-hidden="true"></i>
						<?= __( 'My Favorites' ); ?>
					</label>
				</div>
			</div>
		<# } else { #>
			<div id="gmt-template-library-filter-toolbar-local" class="gmt-template-library-filter-toolbar"></div>
		<# } #>
		<div id="gmt-template-library-filter-text-wrapper">
			<label for="gmt-template-library-filter-text" class="gmt-screen-only"><?= __( 'Search Templates:' ); ?></label>
			<input id="gmt-template-library-filter-text" placeholder="<?= __( 'Search' ); ?>">
			<i class="fas fa-search"></i>
		</div>
	</div>
	<# if ( 'local' === activeSource ) { #>
		<div id="gmt-template-library-order-toolbar-local">
			<div class="gmt-template-library-local-column-1">
				<input type="radio" id="gmt-template-library-order-local-title" class="gmt-template-library-order-input" name="gmt-template-library-order-local" value="title" data-default-ordering-direction="asc">
				<label for="gmt-template-library-order-local-title" class="gmt-template-library-order-label"><?= __( 'Name' ); ?></label>
			</div>
			<div class="gmt-template-library-local-column-2">
				<input type="radio" id="gmt-template-library-order-local-type" class="gmt-template-library-order-input" name="gmt-template-library-order-local" value="type" data-default-ordering-direction="asc">
				<label for="gmt-template-library-order-local-type" class="gmt-template-library-order-label"><?= __( 'Type' ); ?></label>
			</div>
			<div class="gmt-template-library-local-column-3">
				<input type="radio" id="gmt-template-library-order-local-author" class="gmt-template-library-order-input" name="gmt-template-library-order-local" value="author" data-default-ordering-direction="asc">
				<label for="gmt-template-library-order-local-author" class="gmt-template-library-order-label"><?= __( 'Created By' ); ?></label>
			</div>
			<div class="gmt-template-library-local-column-4">
				<input type="radio" id="gmt-template-library-order-local-date" class="gmt-template-library-order-input" name="gmt-template-library-order-local" value="date">
				<label for="gmt-template-library-order-local-date" class="gmt-template-library-order-label"><?= __( 'Creation Date' ); ?></label>
			</div>
			<div class="gmt-template-library-local-column-5">
				<div class="gmt-template-library-order-label"><?= __( 'Actions' ); ?></div>
			</div>
		</div>
	<# } #>
	<div id="gmt-template-library-templates-container"></div>
	<# if ( 'remote' === activeSource ) { #>
		<div id="gmt-template-library-footer-banner">
			<i class="fas fa-glasses" aria-hidden="true"></i>
			<div class="gmt-excerpt"><?= __( 'Stay tuned! More awesome templates coming real soon.' ); ?></div>
		</div>
	<# } #>
    <# if ( goomento.templates.getTemplatesCollection().length ) { #>
        <div class="gmt-template-actions">
            <a href="#" title="<?= __('Load more') ?>" class="gmt-template-load-more"><?= __('Load more') ?></a>
        </div>
    <# } #>
</script>

<script type="text/template" id="tmpl-gmt-template-library-template-remote">
	<div class="gmt-template-library-template-body">
		<# if ( 'page' === type ) { #>
			<div class="gmt-template-library-template-screenshot" style="background-image: url({{ thumbnail }});"></div>
		<# } else { #>
			<img src="{{ thumbnail }}">
		<# } #>
		<div class="gmt-template-library-template-preview">
            <i class="fas fa-search-plus"></i>
		</div>
	</div>
	<div class="gmt-template-library-template-footer">
		{{{ goomento.templates.layout.getTemplateActionButton( obj ) }}}
		<div class="gmt-template-library-template-name">{{{ title }}} - {{{ type }}}</div>
		<div class="gmt-template-library-favorite">
			<input id="gmt-template-library-template-{{ template_id }}-favorite-input" class="gmt-template-library-template-favorite-input" type="checkbox"{{ favorite ? " checked" : "" }}>
			<label for="gmt-template-library-template-{{ template_id }}-favorite-input" class="gmt-template-library-template-favorite-label">
                <i class="far fa-heart"></i>
				<span class="gmt-screen-only"><?= __( 'Favorite' ); ?></span>
			</label>
		</div>
	</div>
</script>

<script type="text/template" id="tmpl-gmt-template-library-template-local">
	<div class="gmt-template-library-template-name gmt-template-library-local-column-1">{{{ title }}}</div>
	<div class="gmt-template-library-template-meta gmt-template-library-template-type gmt-template-library-local-column-2">{{{ goomento.helpers.i18n( type ) }}}</div>
	<div class="gmt-template-library-template-meta gmt-template-library-template-author gmt-template-library-local-column-3">{{{ author }}}</div>
	<div class="gmt-template-library-template-meta gmt-template-library-template-date gmt-template-library-local-column-4">{{{ goomento.helpers.formatDatetime(date) }}}</div>
	<div class="gmt-template-library-template-controls gmt-template-library-local-column-5">
        <#  if ( goomento.userCan( 'view' ) ) { #>
		<div class="gmt-template-library-template-preview">
			<i class="fas fa-eye" aria-hidden="true"></i>
			<span class="gmt-template-library-template-control-title"><?= __( 'Preview' ); ?></span>
		</div>
        <# } #>
        <#  if ( goomento.userCan( 'save' ) ) { #>
		<button class="gmt-template-library-template-action gmt-template-library-template-insert gmt-button gmt-button-success">
			<i class="fas fa-download" aria-hidden="true"></i>
			<span class="gmt-button-title"><?= __( 'Insert' ); ?></span>
		</button>
        <# } #>
        <#  if ( goomento.userCan( 'delete' ) || goomento.userCan( 'export' ) ) { #>
		<div class="gmt-template-library-template-more-toggle">
            <i class="fas fa-ellipsis-h"></i>
			<span class="gmt-screen-only"><?= __( 'More actions' ); ?></span>
		</div>
        <# } #>
		<div class="gmt-template-library-template-more">
            <#  if ( goomento.userCan( 'delete' ) ) { #>
			<div class="gmt-template-library-template-delete">
				<i class="fas fa-trash" aria-hidden="true"></i>
				<span class="gmt-template-library-template-control-title"><?= __( 'Delete' ); ?></span>
			</div>
            <# } #>
            <#  if ( goomento.userCan( 'export' ) ) { #>
			<div class="gmt-template-library-template-export">
				<a href="{{ export_link }}">
					<i class="fas fa-download" aria-hidden="true"></i>
					<span class="gmt-template-library-template-control-title"><?= __( 'Export' ); ?></span>
				</a>
			</div>
            <# } #>
		</div>
	</div>
</script>

<script type="text/template" id="tmpl-gmt-template-library-insert-button">
	<a class="gmt-template-library-template-action gmt-template-library-template-insert gmt-button">
		<i class="fas fa-download" aria-hidden="true"></i>
		<span class="gmt-button-title"><?= __( 'Insert' ); ?></span>
	</a>
</script>

<script type="text/template" id="tmpl-gmt-template-library-save-template">
	<div class="gmt-template-library-blank-icon">
		<i class="fas fa-cloud" aria-hidden="true"></i>
		<span class="gmt-screen-only"><?= __( 'Save' ); ?></span>
	</div>
	<div class="gmt-template-library-blank-title">{{{ title }}}</div>
	<div class="gmt-template-library-blank-message">{{{ description }}}</div>
	<form id="gmt-template-library-save-template-form">
		<input type="hidden" name="content_id" value="<?= $document->getModel()->getId(); ?>">
		<input id="gmt-template-library-save-template-name" name="title" placeholder="<?= __( 'Enter Template Name' ); ?>" required>
		<button id="gmt-template-library-save-template-submit" class="gmt-button gmt-button-success">
			<span class="gmt-state-icon">
				<i class="fa-circle-notch fas spinning" aria-hidden="true"></i>
			</span>
			<?= __( 'Save' ); ?>
		</button>
	</form>
	<div class="gmt-template-library-blank-footer">
	</div>
</script>

<script type="text/template" id="tmpl-gmt-template-library-import">
	<form id="gmt-template-library-import-form">
		<div class="gmt-template-library-blank-icon">
			<i class="fas fa-cloud-upload" aria-hidden="true"></i>
		</div>
		<div class="gmt-template-library-blank-title"><?= __( 'Import Template to Your Library' ); ?></div>
		<div class="gmt-template-library-blank-message"><?= __( 'Drag & drop your .JSON or .zip template file' ); ?></div>
		<div id="gmt-template-library-import-form-or"><?= __( 'or' ); ?></div>
		<label for="gmt-template-library-import-form-input" id="gmt-template-library-import-form-label" class="gmt-button gmt-button-success"><?= __( 'Select File' ); ?></label>
		<input id="gmt-template-library-import-form-input" type="file" name="file" accept=".json,.zip" required/>
		<div class="gmt-template-library-blank-footer">
		</div>
	</form>
</script>

<script type="text/template" id="tmpl-gmt-template-library-templates-empty">
	<div class="gmt-template-library-blank-icon">
		<i class="fas fa-glasses" aria-hidden="true"></i>
	</div>
	<div class="gmt-template-library-blank-title"></div>
	<div class="gmt-template-library-blank-message"></div>
	<div class="gmt-template-library-blank-footer">
	</div>
</script>

<script type="text/template" id="tmpl-gmt-template-library-preview">
	<iframe></iframe>
</script>
