<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Managers\Icons;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();
$settings = $widget->getSettingsForDisplay();

$hasIcon = ! empty($settings['accordion_selected_icon']['value']);
$idInt = substr((string) $widget->getIdInt(), 0, 3); ?>
    <div class="gmt-accordion" role="tablist">
    <?php foreach ($settings['accordion_tabs'] as $index => $item):
        $tabCount = $index + 1;
        $tabTitleSettingKey = 'accordion_tabs.' . $index . '.tab_title';
        $tabContentSettingKey = 'accordion_tabs.' . $index . '.accordion_tab_content';

        $widget->addRenderAttribute($tabTitleSettingKey, [
            'id' => 'gmt-tab-title-' . $idInt . $tabCount,
            'class' => [ 'gmt-tab-title' ],
            'data-tab' => $tabCount,
            'role' => 'tab',
            'aria-controls' => 'gmt-tab-content-' . $idInt . $tabCount,
        ]);

        $widget->addRenderAttribute($tabContentSettingKey, [
            'id' => 'gmt-tab-content-' . $idInt . $tabCount,
            'class' => [ 'gmt-tab-content', 'gmt-clearfix' ],
            'data-tab' => $tabCount,
            'role' => 'tabpanel',
            'aria-labelledby' => 'gmt-tab-title-' . $idInt . $tabCount,
        ]); ?>
        <div class="gmt-accordion-item">
            <<?=  /** @noEscape */ $settings['accordion_title_html_tag']; ?> <?= /** @noEscape */ $widget->getRenderAttributeString($tabTitleSettingKey); ?>>
                <?php if ($hasIcon): ?>
                    <span class="gmt-accordion-icon gmt-accordion-icon-<?= $block->escapeHtmlAttr($settings['accordion_icon_align']); ?>" aria-hidden="true">
                        <span class="gmt-accordion-icon-closed"><?php Icons::renderIcon($settings['accordion_selected_icon']); ?></span>
                        <span class="gmt-accordion-icon-opened"><?php Icons::renderIcon($settings['accordion_selected_active_icon']); ?></span>
                    </span>
                <?php endif; ?>
                <a href=""><?=  /** @noEscape */ $item['accordion_tab_title']; ?></a>
            </<?=  /** @noEscape */ $settings['accordion_title_html_tag']; ?>>

            <div <?= /** @noEscape */ $widget->getRenderAttributeString($tabContentSettingKey); ?>>
                <?php $widget->printInlineEditingContent($tabContentSettingKey, 'advanced'); ?>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
<?php
