<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */
declare(strict_types=1);

use Goomento\Core\Helper\ObjectManagerHelper;
use Goomento\PageBuilder\Block\View\Element\Widget;
use Magento\Catalog\Api\ProductRepositoryInterface;
use Magento\Catalog\Block\Product\ListProduct;
use Magento\Framework\App\Action\Action;
use Magento\Catalog\Model\Product;

// phpcs:disable Magento2.Security.XssTemplate.FoundUnescaped
/**
 * @var Widget $block
 */
$widget = $block->getWidget();
$settings = $block->getSettingsForDisplay();

$productSku = $settings['addcart-button_product'] ?: null;
$postParams = [];
if (trim((string) $productSku)) {
    /** @var ProductRepositoryInterface $productRepository */
    $productRepository = ObjectManagerHelper::create(ProductRepositoryInterface::class);
    try {
        /** @var Product $product */
        $product = $productRepository->get(trim($productSku));
    } catch (\Exception $e) {
    }

    if (isset($product) && $product->getId()) {
        /** @var ListProduct $listBlock */
        $listBlock = ObjectManagerHelper::get(ListProduct::class);
        $postParams = $listBlock->getAddToCartPostParams($product);
    }
}

if (!empty($postParams)):
    $widget->addRenderAttribute('wrapper', 'class', 'gmt-addcart-button-wrapper');
    $widget->addRenderAttribute('button', 'class', 'gmt-button gmt-addcart-button-button');
    $widget->addRenderAttribute('button', 'role', 'button');
    $widget->addRenderAttribute('button', 'type', 'submit');

    if (! empty($settings['addcart-button_css_id'])) {
        $widget->addRenderAttribute('button', 'id', $settings['addcart-button_css_id']);
    }

    if (! empty($settings['addcart-button_size'])) {
        $widget->addRenderAttribute('button', 'class', 'gmt-size-' . $settings['addcart-button_size']);
    }
    if ($settings['addcart-button_hover_animation']) {
        $widget->addRenderAttribute('button', 'class', 'gmt-animation-' . $settings['addcart-button_hover_animation']);
    }
    ?>
    <div <?= /** @noEscape */ $widget->getRenderAttributeString('wrapper'); ?>>
        <form data-product-sku="<?= $block->escapeHtmlAttr($product->getSku()) ?>" action="<?=  /** @noEscape */ $postParams['action'] ?>" data-role="tocart-form" method="post" >
            <input type="hidden"
                   name="product"
                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                   value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
            <?= $block->getBlockHtml('formkey') ?>
            <?= $block->getWidgetHtml('button') ?>
        </form>
        <script type="text/x-magento-init">
                {
                    "[data-role=tocart-form]": {
                        "catalogAddToCart": {
                            "product_sku": "<?= $block->escapeJs($product->getSku()) ?>",
                            "addToCartButtonTextDefault": "<?= /** @noEscape */ $settings['addcart-button_button_text']; ?>",
                            "addToCartButtonSelector": ".gmt-button"
                        }
                    }
                }
        </script>
    </div>
    <?php
endif;
