<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Helper\DataHelper;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();
$settings = $block->getSettingsForDisplay();

if (empty($settings['alert_title'])) {
    return;
}

if (!empty($settings['alert_type'])) {
    $widget->addRenderAttribute('wrapper', 'class', 'gmt-alert gmt-alert-' . $settings['alert_type']);
}

$widget->addRenderAttribute('wrapper', 'role', 'alert');

$widget->addRenderAttribute('alert_title', 'class', 'gmt-alert-title');

$widget->addInlineEditingAttributes('alert_title', 'none'); ?>
<div <?= $widget->getRenderAttributeString('wrapper'); ?>>
    <span <?= $widget->getRenderAttributeString('alert_title'); ?>><?= $settings['alert_title']; ?></span>
    <?php
    if (!DataHelper::isEmpty($settings['alert_description'])) :
        $widget->addRenderAttribute('alert_description', 'class', 'gmt-alert-description');

        $widget->addInlineEditingAttributes('alert_description'); ?>
        <span <?= $widget->getRenderAttributeString('alert_description'); ?>><?= $settings['alert_description']; ?></span>
    <?php endif; ?>
    <?php if ('show' === $settings['alert_show_dismiss']) : ?>
        <button type="button" class="gmt-alert-dismiss">
            <span aria-hidden="true">&times;</span>
            <span class="gmt-screen-only"><?= __('Dismiss alert'); ?></span>
        </button>
    <?php endif; ?>
</div>
