<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Widgets\Banner;
use Goomento\PageBuilder\Builder\Widgets\ImageCarousel;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();
$settings = $block->getSettingsForDisplay();

if (!empty($settings['banner-slider_list'])):
    $widget->addRenderAttribute('_wrapper', 'class', 'gmt-invisible');
    ?>
    <div class="gmt-banner-slider-wrapper swiper-container">
        <div class="gmt-banner-carousel swiper-wrapper">
            <?php
            foreach ($settings['banner-slider_list'] as $index => $banner):
                $linkSettingKey = implode('.', [
                    'banner-slider_list',
                    $index,
                    $widget::NAME
                ]) . '_';
                ?>
                <div class="gmt-banner-slider-item swiper-slide">
                        <?php
                        $bannerSettings = $settings;
                        unset($bannerSettings['banner-slider_list']);
                        $bannerSettings['banner_image_classes'] = 'swiper-slide-image';
                        ?>
                        <?= $block->getWidgetHtml(
                            Banner::NAME,
                            null,
                            $linkSettingKey,
                            $banner + $bannerSettings
                        ); ?>
                </div>
            <?php endforeach; ?>
        </div>
        <?php
        if (count($settings['banner-slider_list']) > 1):
            ImageCarousel::printCarouselControls(
                in_array($settings['navigation'], [ 'dots', 'both' ]),
                in_array($settings['navigation'], [ 'arrows', 'both' ])
            );
        endif;
        ?>
    </div>
<?php endif; ?>


