<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Controls\Groups\ImageSizeGroup;
use Goomento\PageBuilder\Builder\Widgets\Button;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();

$settings = $block->getSettingsForDisplay();
$title = $settings['banner_title'] ?? '';
$caption = $settings['banner_caption'] ?? '';

$hasContent = !empty($title) || !empty($caption) || $settings['banner_button_show'] === 'yes';

if (!empty($settings['banner_image']['url'])):
    if (!empty($settings['banner_link']['url'])) {
        $widget->addRenderAttribute('link', 'href', $settings['banner_link']['url']);

        if ($settings['banner_link']['is_external']) {
            $widget->addRenderAttribute('link', 'target', '_blank');
        }

        if (!empty($settings['banner_link']['nofollow'])) {
            $widget->addRenderAttribute('link', 'rel', 'nofollow');
        }
    }

    $imageHtml = ImageSizeGroup::getAttachmentImageHtml($settings, 'banner_image', 'thumbnail');

    if (!empty($settings['banner_link']['url'])) {
        $imageHtml = '<a ' . $widget->getRenderAttributeString('link') . '>' . $imageHtml . '</a>';
    }
    ?>
    <div class="gmt-banner-wrapper">
        <figure class="gmt-banner-img"><?= /** @noEscape */ $imageHtml ?></figure>
        <?php
        if ($hasContent):
            $widget->addRenderAttribute('box-content', 'class', 'gmt-banner-content');
            $widget->addRenderAttribute('box-content', 'class', 'gmt-banner-content-position-' . ($settings['banner_caption_position'] ?? ''));
            ?>
            <div <?= /** @noEscape */ $widget->getRenderAttributeString('box-content') ?>>
                <?php
                if ($title):
                    $widget->addRenderAttribute('title', 'class', 'gmt-banner-title'); ?>
                    <div <?= /** @noEscape */ $widget->getRenderAttributeString('title') ?>>
                        <?php $widget->printInlineEditingContent('banner_title'); ?>
                    </div>
                    <?php
                endif;
                if ($caption):
                    $widget->addRenderAttribute('caption', 'class', 'gmt-banner-description');
                    ?>
                    <div <?= /** @noEscape */ $widget->getRenderAttributeString('caption') ?>>
                        <?php $widget->printInlineEditingContent('banner_caption'); ?>
                    </div>
                <?php  endif; ?>
                <?php if ($settings['banner_button_show'] === 'yes'): ?>
                    <?= $block->getWidgetHtml(Button::NAME) ?>
                <?php endif; ?>
            </div>
        <?php endif;  ?>
    </div>
    <?php
endif;
