<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();

$settings = $block->getSettingsForDisplay();
$title = trim((string) $settings['banner_title']);
$caption = trim((string) $settings['banner_caption']);

$hasContent = !empty($title) || !empty($caption);

if (!empty($settings['banner_image']['url'])) :
    if (!empty($settings['banner_link']['url'])) {
        $widget->addRenderAttribute('link', 'href', $settings['banner_link']['url']);

        if ($settings['banner_link']['is_external']) {
            $widget->addRenderAttribute('link', 'target', '_blank');
        }

        if (!empty($settings['banner_link']['nofollow'])) {
            $widget->addRenderAttribute('link', 'rel', 'nofollow');
        }
    }

    $widget->addRenderAttribute('image', 'src', $settings['banner_image']['url']);
    $widget->addRenderAttribute('image', 'alt', '');
    $widget->addRenderAttribute('image', 'title', '');

    if ($settings['banner_hover_animation']) {
        $widget->addRenderAttribute('image', 'class', 'gmt-animation-' . $settings['banner_hover_animation']);
    }
    $image_html = '<img ' . $widget->getRenderAttributeString('image') . '/>';

    if (!empty($settings['banner_link']['url'])) {
        $image_html = '<a ' . $widget->getRenderAttributeString('link') . '>' . $image_html . '</a>';
    }
    ?>
    <div class="gmt-banner-wrapper">
        <figure class="gmt-banner-img"><?= /** @noEscape  */ $image_html ?></figure>
        <?php
        if ($hasContent) :
            $widget->addRenderAttribute('box-content', 'class', 'gmt-banner-content');
            $widget->addRenderAttribute('box-content', 'class', 'gmt-banner-content-position-' . ($settings['banner_caption_position'] ?? ''));
            ?>
            <div <?= $widget->getRenderAttributeString('box-content') ?>>
                <?php
                if ($title) :
                    $widget->addInlineEditingAttributes(['title' => 'banner_title']);
                    $widget->addRenderAttribute('title', 'class', 'gmt-banner-title'); ?>
                    <div <?= $widget->getRenderAttributeString('title') ?>><?= /** @noEscape */ $title ?></div>
                    <?php
                endif;
                if ($caption) :
                    $widget->addRenderAttribute('caption', 'class', 'gmt-banner-description');
                    $widget->addInlineEditingAttributes(['caption' => 'banner_caption']);
                    ?>
                    <div <?= $widget->getRenderAttributeString('caption') ?>><?= /** @noEscape */ $caption ?></div>
                <?php  endif; ?>
            </div>
        <?php endif;  ?>
    </div>
<?php
endif;
