<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Helper\DataHelper;
use Magento\Framework\Escaper;
/**
 * @var Widget $block
 * @var Escaper $escaper
 */
$widget = $block->getWidget();

$settings = $block->getSettingsForDisplay();

$hasContent = !DataHelper::isEmpty($settings['banner_caption']);

if (!empty($settings['banner_image']['url'])) :
    if (!empty($settings['banner_link']['url'])) {
        $widget->addRenderAttribute('link', 'href', $settings['banner_link']['url']);

        if ($settings['banner_link']['is_external']) {
            $widget->addRenderAttribute('link', 'target', '_blank');
        }

        if (!empty($settings['banner_link']['nofollow'])) {
            $widget->addRenderAttribute('link', 'rel', 'nofollow');
        }
    }

    $widget->addRenderAttribute('image', 'src', $settings['banner_image']['url']);
    $widget->addRenderAttribute('image', 'alt', '');
    $widget->addRenderAttribute('image', 'title', '');

    if ($settings['banner_hover_animation']) {
        $widget->addRenderAttribute('image', 'class', 'gmt-animation-' . $settings['banner_hover_animation']);
    }
    $image_html = '<img ' . $widget->getRenderAttributeString('image') . '/>';
    if (!empty($settings['banner_link']['url'])) {
        $image_html = '<a ' . $widget->getRenderAttributeString('link') . '>' . $image_html . '</a>';
    }
    ?>
    <div class="gmt-banner-wrapper">
        <figure class="gmt-banner-img"><?= /** @noEscape  */ $image_html ?></figure>
        <?php
        if ($hasContent) :
            $widget->addRenderAttribute('box-content', 'class', 'gmt-banner-content');
            $widget->addRenderAttribute('box-content', 'class', 'gmt-banner-content-position-' . ($settings['banner_caption_position'] ?? ''));
            ?>
            <div <?= $widget->getRenderAttributeString('box-content') ?>>
                <?php
                if (!DataHelper::isEmpty($settings['banner_caption'])) :
                    $widget->addRenderAttribute('caption', 'class', 'gmt-banner-description');

                    $widget->addInlineEditingAttributes('caption');
                    ?>
                    <div <?= $widget->getRenderAttributeString('caption') ?>><?= $escaper->escapeHtml($settings['banner_caption']) ?></div>
                <?php  endif; ?>
            </div>
        <?php endif;  ?>
    </div>
<?php
endif;
