<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Widgets\Icon;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();

$settings = $widget->getSettingsForDisplay();

$iconTag = 'span';
if (!empty($settings['icon-box_icon_link']['url'])) {
    $widget->addRenderAttribute('link', 'href', $settings['icon-box_icon_link']['url']);
    $iconTag = 'a';

    if ($settings['icon-box_icon_link']['is_external']) {
        $widget->addRenderAttribute('link', 'target', '_blank');
    }

    if ($settings['icon-box_icon_link']['nofollow']) {
        $widget->addRenderAttribute('link', 'rel', 'nofollow');
    }
}

$linkAttributes = $widget->getRenderAttributeString('link');
$widget->addRenderAttribute('description_text', 'class', 'gmt-icon-box-description');

?>
<div class="gmt-icon-box-wrapper">
    <div class="gmt-icon-box-icon">
        <?= /** @noEscape  */ $block->getWidgetHtml(Icon::NAME) ?>
    </div>
    <div class="gmt-icon-box-content">
        <<?=  /** @noEscape */ $settings['icon-box_title_size']; ?> class="gmt-icon-box-title">
            <<?= /** @noEscape */ implode(' ', [ $iconTag, $linkAttributes ]); ?> <?= /** @noEscape */ $widget->getRenderAttributeString('title_text'); ?>>
                <?php $widget->printInlineEditingContent('icon-box_title_text'); ?>
            </<?=  /** @noEscape */ $iconTag; ?>>
        </<?=  /** @noEscape */ $settings['icon-box_title_size']; ?>>
        <?php if (!empty($settings['icon-box_description_text'])): ?>
            <div <?= /** @noEscape */ $widget->getRenderAttributeString('description_text'); ?>>
                <?php $widget->printInlineEditingContent('icon-box_description_text', 'none', 'span'); ?>
            </div>
        <?php endif; ?>
    </div>
</div>
