<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Managers\Icons;
use Goomento\PageBuilder\Helper\DataHelper;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();

$settings = $widget->getSettingsForDisplay();

$widget->addRenderAttribute('icon', 'class', [ 'gmt-icon', 'gmt-animation-' . $settings['hover_animation'] ]);

$iconTag = 'span';

$hasIcon = !empty($settings['selected_icon']['value']);

if (!empty($settings['link']['url'])) {
    $widget->addRenderAttribute('link', 'href', $settings['link']['url']);
    $iconTag = 'a';

    if ($settings['link']['is_external']) {
        $widget->addRenderAttribute('link', 'target', '_blank');
    }

    if ($settings['link']['nofollow']) {
        $widget->addRenderAttribute('link', 'rel', 'nofollow');
    }
}

if ($hasIcon) {
    $widget->addRenderAttribute('i', 'class', $settings['selected_icon']['library']);
    $widget->addRenderAttribute('i', 'aria-hidden', 'true');
}

$iconAttributes = $widget->getRenderAttributeString('icon');
$linkAttributes = $widget->getRenderAttributeString('link');

$widget->addRenderAttribute('description_text', 'class', 'gmt-icon-box-description');

$widget->addInlineEditingAttributes('title_text', 'none');
$widget->addInlineEditingAttributes('description_text');
?>
<div class="gmt-icon-box-wrapper">
    <?php if ($hasIcon) : ?>
    <div class="gmt-icon-box-icon">
        <<?= implode(' ', [ $iconTag, $iconAttributes, $linkAttributes ]); ?>>
            <?php Icons::renderIcon($settings['selected_icon'], [ 'aria-hidden' => 'true' ]); ?>
        </<?= $iconTag; ?>>
    </div>
    <?php endif; ?>
    <div class="gmt-icon-box-content">
        <<?= $settings['title_size']; ?> class="gmt-icon-box-title">
            <<?= implode(' ', [ $iconTag, $linkAttributes ]); ?><?= $widget->getRenderAttributeString('title_text'); ?>><?= $settings['title_text']; ?></<?= $iconTag; ?>>
        </<?= $settings['title_size']; ?>>
        <?php if (!empty($settings['description_text'])) : ?>
            <p <?= $widget->getRenderAttributeString('description_text'); ?>><?= /** @noEscape */ $settings['description_text']; ?></p>
        <?php endif; ?>
    </div>
</div>
