<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Managers\Icons;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();

$settings = $widget->getSettingsForDisplay();

$fallbackDefaults = [
    'fas fa-check',
    'fas fa-times',
    'fas fa-dot-circle-o',
];

$widget->addRenderAttribute('icon_list', 'class', 'gmt-icon-list-items');
$widget->addRenderAttribute('list_item', 'class', 'gmt-icon-list-item');

if ('inline' === $settings['icon_list_view']) {
    $widget->addRenderAttribute('icon_list', 'class', 'gmt-inline-items');
    $widget->addRenderAttribute('list_item', 'class', 'gmt-inline-item');
} ?>
<ul <?= /** @noEscape */ $widget->getRenderAttributeString('icon_list'); ?>>
    <?php
    foreach ($settings['icon_list_icon_list'] as $index => $item):
        $key = 'icon_list_icon_list.' . $index . '.text';
        $widget->addRenderAttribute($key, 'class', 'gmt-icon-list-text');
        ?>
        <li class="gmt-icon-list-item" >
            <?php
            if (!empty($item['link']['url'])) {
                $linkKey = 'link_' . $index;

                $widget->addRenderAttribute($linkKey, 'href', $item['link']['url']);

                if ($item['link']['is_external']) {
                    $widget->addRenderAttribute($linkKey, 'target', '_blank');
                }

                if ($item['link']['nofollow']) {
                    $widget->addRenderAttribute($linkKey, 'rel', 'nofollow');
                }

                echo '<a ' . /** @noEscape */ $widget->getRenderAttributeString($linkKey) . '>';
            }

            // add old default
            if (! isset($item['icon'])) {
                $item['icon'] = $fallbackDefaults[$index] ?? 'fas fa-check';
            }

            if (!empty($item['icon']) || (! empty($item['selected_icon']['value']))): ?>
                <span class="gmt-icon-list-icon">
                    <?php Icons::renderIcon($item['selected_icon'], [ 'aria-hidden' => 'true' ]); ?>
                </span>
            <?php endif; ?>
                <span <?= /** @noEscape */ $widget->getRenderAttributeString($key); ?>>
                    <?php $widget->printInlineEditingContent($key); ?>
                </span>
            <?php if (!empty($item['link']['url'])): ?>
                </a>
            <?php endif; ?>
        </li>
        <?php
    endforeach; ?>
</ul>
