<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Controls\Groups\ImageSizeGroup;
use Goomento\PageBuilder\Builder\Widgets\Image;

/**
 * @var Widget $block
 * @var Image $widget
 */
$widget = $block->getWidget();
$settings = $widget->getSettingsForDisplay();

if (empty($settings['image_image']['url'])) {
    return;
}

$caption = $settings['image_caption_source'] === 'custom' ? $settings['image_caption'] : '';
$hasCaption = !!$caption;

$widget->addRenderAttribute('wrapper', 'class', 'gmt-image');

if (!empty($settings['image_shape'])) {
    $widget->addRenderAttribute('wrapper', 'class', 'gmt-image-shape-' . $settings['image_shape']);
}

if ('none' === $settings['image_link_to']) {
    $link = false;
} elseif ('custom' === $settings['image_link_to']) {
    $link = $settings['image_link'];
} else {
    $link = [
        'url' => $settings['image_image']['url']
    ];
}

if ($link) {
    $widget->addRenderAttribute('link', [
        'href' => $link['url'],
        'data-gmt-open-lightbox' => $settings['image_open_lightbox'],
    ]);
    
    if (!empty($link['is_external'])) {
        $widget->addRenderAttribute('link', 'target', '_blank');
    }

    if (!empty($link['nofollow'])) {
        $widget->addRenderAttribute('link', 'rel', 'nofollow');
    }
} ?>
<div <?= /** @noEscape */ $widget->getRenderAttributeString('wrapper'); ?>>
    <?php if ($hasCaption): ?>
        <figure class="gmt-caption">
    <?php endif; ?>
        <?php if ($link): ?>
            <a <?= /** @noEscape */ $widget->getRenderAttributeString('link'); ?>>
                <?php endif; ?>
                <?= /** @noEscape */ ImageSizeGroup::getAttachmentImageHtml($settings, 'image_image'); ?>
                <?php if ($link): ?>
            </a>
        <?php endif; ?>
        <?php if ($hasCaption): ?>
            <figcaption class="widget-image-caption image-caption-text">
                <?= /** @noEscape */ $settings['image_caption_source'] === 'custom' ? /** @noEscape */ $settings['image_caption'] : ''; ?>
            </figcaption>
        <?php endif; ?>
    <?php if ($hasCaption): ?>
        </figure>
    <?php endif; ?>
</div>
