<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Widgets\ImageCarousel;
use Goomento\PageBuilder\Builder\Controls\Groups\ImageSizeGroup;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();
$settings = $block->getSettingsForDisplay();

if (empty($settings['image-carousel_carousel'])) {
    return;
}

$slides = [];

foreach ($settings['image-carousel_carousel'] as $index => $attachment) {

    $imageHtml = ImageSizeGroup::getAttachmentImageHtml(array_merge($settings, [
        'image-carousel_thumbnail' => $attachment
    ]), 'image-carousel_thumbnail');

    $linkTag = '';

    $link = [];

    if ('custom' === $settings['link_to']) {
        if (!empty($settings['link']['url'])) {
            $link = $settings['link'];
        }
    } elseif ('none' !== $settings['link_to']) {
        $link['url'] = $attachment['url'];
    }

    if (!empty($link)) {
        $linkKey = 'link_' . $index;
        $widget->addRenderAttribute($linkKey, [
            'href' => $link['url'],
            'data-gmt-open-lightbox' => $settings['open_lightbox'],
            'data-gmt-lightbox-slideshow' => $widget->getId(),
            'data-gmt-lightbox-index' => $index,
        ]);

        if (! empty($link['is_external'])) {
            $widget->addRenderAttribute($linkKey, 'target', '_blank');
        }

        if (! empty($link['nofollow'])) {
            $widget->addRenderAttribute($linkKey, 'rel', 'nofollow');
        }

        $linkTag = '<a ' . $widget->getRenderAttributeString($linkKey) . '>';
    }

    $slideHtml = '<div class="swiper-slide">' . $linkTag . '<figure class="swiper-slide-inner">' . $imageHtml;


    $slideHtml .= '</figure>';

    if ($link) {
        $slideHtml .= '</a>';
    }

    $slideHtml .= '</div>';

    $slides[] = $slideHtml;
}

if (!empty($slides)):
    $widget->addRenderAttribute('_wrapper', 'class', 'gmt-invisible');

    $widget->addRenderAttribute([
        'carousel' => [
            'class' => 'gmt-image-carousel swiper-wrapper',
        ],
        'carousel-wrapper' => [
            'class' => 'gmt-image-carousel-wrapper swiper-container',
            'dir' => $settings['direction'],
        ],
    ]);

    $showDots = (in_array($settings['navigation'], [ 'dots', 'both' ]));
    $showArrows = (in_array($settings['navigation'], [ 'arrows', 'both' ]));

    if ('yes' === $settings['image_stretch']) {
        $widget->addRenderAttribute('carousel', 'class', 'swiper-image-stretch');
    }

    $slidesCount = count($settings['image-carousel_carousel']); ?>
    <div <?= /** @noEscape */ $widget->getRenderAttributeString('carousel-wrapper'); ?>>
        <div <?= /** @noEscape */ $widget->getRenderAttributeString('carousel'); ?>>
            <?= /** @noEscape */ implode('', $slides); ?>
        </div>
        <?php if (1 < $slidesCount):
            ImageCarousel::printCarouselControls(
                $showDots,
                $showArrows
            );
        endif; ?>
    </div>
    <?php
endif;

