<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Controls\Groups\ImageSizeGroup;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();
$settings = $widget->getSettingsForDisplay();
$has_content = !empty($settings['title_text']) || !empty($settings['description_text']);
?>
<div class="gmt-image-box-wrapper">
    <?php
    if (!empty($settings['link']['url'])) {
        $widget->addRenderAttribute('link', 'href', $settings['link']['url']);

        if ($settings['link']['is_external']) {
            $widget->addRenderAttribute('link', 'target', '_blank');
        }

        if (!empty($settings['link']['nofollow'])) {
            $widget->addRenderAttribute('link', 'rel', 'nofollow');
        }
    }

    if (!empty($settings['image']['url'])) {

        $image_html = ImageSizeGroup::getAttachmentImageHtml($settings);

        if (!empty($settings['link']['url'])) {
            $image_html = '<a ' . $widget->getRenderAttributeString('link') . '>' . $image_html . '</a>';
        }
        ?>
        <figure class="gmt-image-box-img"><?= $image_html ?></figure>
        <?php
    }

    if ($has_content) : ?>
        <div class="gmt-image-box-content">
            <?php
            if (!empty($settings['title_text'])) :
                $widget->addRenderAttribute('title_text', 'class', 'gmt-image-box-title');

                $widget->addInlineEditingAttributes('title_text', 'none');

                $title_html = $settings['title_text'];

                if (!empty($settings['link']['url'])) {
                    $title_html = '<a ' . $widget->getRenderAttributeString('link') . '>' . $title_html . '</a>';
                }

                ?>
                <<?= $settings['title_size'] ?> <?= $widget->getRenderAttributeString('title_text') ?>>
                    <?= $title_html ?>
                </<?= $settings['title_size'] ?>>
                <?php
            endif;

            if (!empty($settings['description_text'])) :
                $widget->addRenderAttribute('description_text', 'class', 'gmt-image-box-description');

                $widget->addInlineEditingAttributes('description_text');

                ?>
                <p <?= $widget->getRenderAttributeString('description_text') ?>>
                    <?= /** @noEscape */ $settings['description_text'] ?>
                </p>
            <?php endif ?>
        </div>
    <?php endif; ?>
</div>

