<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Helper\EscaperHelper;
use Goomento\PageBuilder\Helper\StateHelper;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();
$settings = $block->getSettingsForDisplay();

if (empty($settings['image-carousel_carousel'])) {
    return;
}

$slides = [];

foreach ($settings['image-carousel_carousel'] as $index => $attachment) {
    $imageUrl = $attachment['url'];

    $imageHtml = '<img class="swiper-slide-image" src="' . EscaperHelper::escapeHtml($imageUrl) . '" alt="" />';

    $linkTag = '';

    $link = [];

    if ('custom' === $settings['image-carousel_link_to']) {
        if (!empty($settings['image-carousel_link']['url'])) {
            $link = $settings['image-carousel_link'];
        }
    } elseif ('none' !== $settings['image-carousel_link_to']) {
        $link['url'] = $attachment['url'];
    }

    if (!empty($link)) {

        $linkKey = 'link_' . $index;
        $widget->addRenderAttribute($linkKey, [
            'href' => $link['url'],
            'data-gmt-open-lightbox' => $settings['image-carousel_open_lightbox'],
            'data-gmt-lightbox-slideshow' => $widget->getId(),
            'data-gmt-lightbox-index' => $index,
        ]);

        if (StateHelper::isEditorMode()) {
            $widget->addRenderAttribute($linkKey, [
                'class' => 'gmt-clickable',
            ]);
        }

        if (! empty($link['is_external'])) {
            $widget->addRenderAttribute($linkKey, 'target', '_blank');
        }

        if (! empty($link['nofollow'])) {
            $widget->addRenderAttribute($linkKey, 'rel', 'nofollow');
        }

        $linkTag = '<a ' . $widget->getRenderAttributeString($linkKey) . '>';
    }

    $slideHtml = '<div class="swiper-slide">' . $linkTag . '<figure class="swiper-slide-inner">' . $imageHtml;


    $slideHtml .= '</figure>';

    if ($link) {
        $slideHtml .= '</a>';
    }

    $slideHtml .= '</div>';

    $slides[] = $slideHtml;
}

if (!empty($slides)) :
    $widget->addRenderAttribute('_wrapper', 'class', 'gmt-invisible');

    $widget->addRenderAttribute([
        'carousel' => [
            'class' => 'gmt-image-carousel swiper-wrapper',
        ],
        'carousel-wrapper' => [
            'class' => 'gmt-image-carousel-wrapper swiper-container',
            'dir' => $settings['direction'],
        ],
    ]);

    $showDots = (in_array($settings['navigation'], [ 'dots', 'both' ]));
    $showArrows = (in_array($settings['navigation'], [ 'arrows', 'both' ]));

    if ('yes' === $settings['image-carousel_image_stretch']) {
        $widget->addRenderAttribute('carousel', 'class', 'swiper-image-stretch');
    }

    $slidesCount = count($settings['image-carousel_carousel']); ?>
    <div <?= $widget->getRenderAttributeString('carousel-wrapper'); ?>>
        <div <?= $widget->getRenderAttributeString('carousel'); ?>>
            <?= implode('', $slides); ?>
        </div>
        <?php if (1 < $slidesCount) : ?>
            <?php if ($showDots) : ?>
                <div class="swiper-pagination"></div>
            <?php endif; ?>
            <?php if ($showArrows) : ?>
                <div class="gmt-swiper-button gmt-swiper-button-prev">
                    <i class="fa fa-chevron-left" aria-hidden="true"></i>
                    <span class="gmt-screen-only"><?php __('Previous'); ?></span>
                </div>
                <div class="gmt-swiper-button gmt-swiper-button-next">
                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                    <span class="gmt-screen-only"><?php __('Next'); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
<?php
endif;

