<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();
$settings = $widget->getSettingsForDisplay();

$progressPercentage = is_numeric($settings['progress_percent']['size']) ? $settings['progress_percent']['size'] : '0';
if (100 < $progressPercentage) {
    $progressPercentage = 100;
}

$widget->addRenderAttribute('wrapper', [
    'class' => 'gmt-progress-wrapper',
    'role' => 'progressbar',
    'aria-valuemin' => '0',
    'aria-valuemax' => '100',
    'aria-valuenow' => $progressPercentage,
    'aria-valuetext' => (string) $settings['progress_inner_text'],
]);

if (!empty($settings['progress_type'])) {
    $widget->addRenderAttribute('wrapper', 'class', 'progress-' . $settings['progress_type']);
}

$widget->addRenderAttribute('progress-bar', [
    'class' => 'gmt-progress-bar',
    'data-max' => $progressPercentage,
]);

$widget->addRenderAttribute('inner_text', [
    'class' => 'gmt-progress-text',
]);

$widget->addRenderAttribute('progress_title', [
    'class' => 'gmt-title',
]);

$widget->addInlineEditingAttributes(['inner_text' => 'progress_inner_text']);
$widget->addInlineEditingAttributes('progress_title');

if (!empty($settings['progress_title'])) { ?>
    <span <?= /** @noEscape */ $widget->getRenderAttributeString('progress_title'); ?>><?=  /** @noEscape */ $settings['progress_title']; ?></span>
<?php } ?>

<div <?= /** @noEscape */ $widget->getRenderAttributeString('wrapper'); ?>>
    <div <?= /** @noEscape */ $widget->getRenderAttributeString('progress-bar'); ?>>
        <span <?= /** @noEscape */ $widget->getRenderAttributeString('inner_text'); ?>><?=  /** @noEscape */ $settings['progress_inner_text']; ?></span>
        <?php if ('hide' !== $settings['progress_display_percentage']) { ?>
            <span class="gmt-progress-percentage"><?=  /** @noEscape */ $progressPercentage; ?>%</span>
        <?php } ?>
    </div>
</div>
