<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Magento\Framework\App\Action\Action;
use Goomento\PageBuilder\Builder\Widgets\ImageCarousel;

/**
 * @var \Goomento\PageBuilder\Block\Widgets\Product\ProductList $block
 * @var \Goomento\PageBuilder\Builder\Widgets\ProductList $widget
 */
$widget = $block->getWidget();
$name = $widget->getName();

/**
 * Modified from Magento_CatalogWidget::product/widget/content/grid.phtml
 * @see Magento_CatalogWidget::product/widget/content/grid.phtml
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php

    $isSlideMode = (bool) $block->getSettingsForDisplay('navigation');

    $type = 'widget-product-grid';

    $mode = $block->getMode() ?: 'grid';

    $image = $block->getMode() === 'grid' ? 'category_page_grid' : 'category_page_list';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;

    $widget->addRenderAttribute('products-list', 'class', 'block widget block-products-list ' . $mode);
    $widget->addRenderAttribute('items-wrapper', 'class', 'gmt-products-' . $mode . ' ' . $mode);
    $widget->addRenderAttribute('items', 'class', 'gmt-product-items product-items ' . $type);
    $widget->addRenderAttribute('item', 'class', 'item gmt-product gmt-product-item product-item');

    if (!$isSlideMode) {
        $widget->addRenderAttribute('items', 'class', 'gmt-row');
        if ($block->getSettingsForDisplay($name . '_products_per_row') && $block->getMode() === 'grid') {
            $widget->addRenderAttribute('item', 'class', 'gmt-column');
            $widget->addRenderAttribute('item', 'class', 'gmt-col-' . $block->getSettingsForDisplay($name . '_products_per_row'));
            $widget->addRenderAttribute('item', 'class', 'gmt-md-' . $block->getSettingsForDisplay($name . '_products_per_row_tablet'));
            $widget->addRenderAttribute('item', 'class', 'gmt-sm-' . $block->getSettingsForDisplay($name . '_products_per_row_mobile'));
        }
    }

    ?>
    <div <?= /** @noEscape */ $widget->getRenderAttributeString('products-list') ?>>
        <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
        <div <?= /** @noEscape */ $widget->getRenderAttributeString('items-wrapper') ?>>
            <ol <?= /** @noEscape */ $widget->getRenderAttributeString('items') ?>>
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                    <?= /* @noEscape */ ($iterator++ == 1) ? '<li ' . $widget->getRenderAttributeString('item') . '>'
                        : '</li><li ' . $widget->getRenderAttributeString('item') . '>' ?>
                    <div class="product-item-info">
                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                            <?= $block->getImage($_item, $image)->toHtml() ?>
                        </a>
                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                   href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($_item->getName()) ?>
                                </a>
                            </strong>
                            <?php if ($templateType): ?>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?= $block->getProductPriceHtml($_item, $type) ?>

                            <?= $block->getProductDetailsHtml($_item) ?>

                            <?php if ($showWishlist || $showCompare || $showCart): ?>
                                <div class="product-item-inner">
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                    <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                        <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                class="action tocart primary">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php //phpcs:disable ?>
                                                <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                                    <?php //phpcs:enable ?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php //phpcs:disable ?>
                                                    <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                    <?php //phpcs:enable ?>
                                                    <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
            <?php if (!$isSlideMode): ?>
                <?= $block->getPagerHtml(); ?>
            <?php else: ?>
                <?php
                $navigation = $block->getSettingsForDisplay('navigation');
                $showDots = in_array($navigation, [ 'dots', 'both' ]);
                $showArrows = in_array($navigation, [ 'arrows', 'both' ]);
                $slidesCount = $block->getProductCollection()->count();

                if (1 < $slidesCount):
                    ImageCarousel::printCarouselControls(
                        $showDots,
                        $showArrows
                    );
                endif; ?>
            <?php endif; ?>
        </div>
        <?php if (!$block->isRedirectToCartEnabled()):?>
            <script type="text/x-magento-init">
                {
                    "[data-role=tocart-form], .form.map.checkout": {
                        "catalogAddToCart": {
                            "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                        }
                    }
                }
                </script>
        <?php endif; ?>
    </div>
<?php endif;?>

