<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */
declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Block\Widgets\Product\ListProduct;
use Goomento\PageBuilder\Builder\Widgets\ProductSlider;
use Goomento\PageBuilder\Helper\DataHelper;
use Goomento\PageBuilder\Helper\LayoutHelper;

/**
 * @var Widget $block
 * @var ProductSlider $widget
 */
$widget = $block->getWidget();
$settings = $block->getSettingsForDisplay();
$category = $settings['product-slider_category'];
$product = $settings['product-slider_product'];
$categoryIds = DataHelper::extractStr($category);
$productSkus = DataHelper::extractStr($product);

if (!empty($categoryIds) || !empty($productSkus)) :
    ?>
    <div class="gmt-product-list-wrapper">
        <div class="gmt-product-list-inner">
            <?php
            if ($productSkus || $categoryIds) :

                $widget->addRenderAttribute([
                    'item' => [
                        'class' => 'swiper-slide',
                    ],
                    'items' => [
                        'class' => 'gmt-product-carousel swiper-wrapper',
                    ],
                    'items-wrapper' => [
                        'class' => 'gmt-product-carousel-wrapper swiper-container',
                        'dir' => $settings['direction'],
                    ],
                ]);

                /** @var ListProduct $blockList */
                $blockList = LayoutHelper::getBlock('pagebuilder.products.list');
                $blockList
                    ->setTemplate('Goomento_PageBuilder::widgets/product/slider.phtml')
                    ->setProductsPerPage($settings['product-slider_products_per_page'] ?: 12)
                    ->setProductSkus($productSkus)
                    ->setCategoryIds($categoryIds)
                    ->setWidget($widget);
                ?>

                <?= /** @noEscape */ $blockList->toHtml() ?>
            <?php endif; ?>
        </div>
    </div>
<?php  endif; ?>

