<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Managers\Icons;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();
$settings = $widget->getSettingsForDisplay();

$classAnimation = '';

if (!empty($settings['social_icons_hover_animation'])) {
    $classAnimation = ' gmt-animation-' . $settings['social_icons_hover_animation'];
}
?>
<div class="gmt-social-icons-wrapper">
    <?php
    foreach ($settings['social_icons_list'] as $index => $item):
        $social = '';

        if (isset($item['social_icon']['value']) && $item['social_icon']['value']) {
            $value = explode(' ', $item['social_icon']['value']);
            $social = str_replace('fa-', '', $value[1]);
        }

        $linkKey = 'link_' . $index;

        $widget->addRenderAttribute($linkKey, 'href', $item['link']['url']);

        $className = str_replace('fab fa-', '', $social);
        $className = str_replace('fas fa-', '', $className);

        $widget->addRenderAttribute($linkKey, 'class', [
            'gmt-icon',
            'gmt-social-icon',
            'gmt-social-icon-' . $className . $classAnimation,
            'gmt-repeater-item-' . ($item['_id'] ?? ''),
        ]);

        if ($item['link']['is_external']) {
            $widget->addRenderAttribute($linkKey, 'target', '_blank');
        }

        if ($item['link']['nofollow']) {
            $widget->addRenderAttribute($linkKey, 'rel', 'nofollow');
        } ?>
        <a <?= /** @noEscape */ $widget->getRenderAttributeString($linkKey); ?>>
            <span class="gmt-screen-only"><?= /** @noEscape */ ucwords($social); ?></span>
            <?php Icons::renderIcon($item['social_icon']); ?>
        </a>
    <?php endforeach; ?>
</div>
