<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Managers\Icons;
use Magento\Framework\Escaper;

/**
 * @var Widget $block
 * @var Escaper $escaper
 */
$widget = $block->getWidget();
$settings = $widget->getSettingsForDisplay();

$fallback_defaults = [
    'fab fa-facebook',
    'fab fa-twitter',
    'fab fa-google-plus',
];

$class_animation = '';

if (!empty($settings['hover_animation'])) {
    $class_animation = ' gmt-animation-' . $settings['hover_animation'];
}
?>
<div class="gmt-social-icons-wrapper">
    <?php
    foreach ($settings['social_icon_list'] as $index => $item) {
        $social = '';

        // add old default
        if (empty($item['social'])) {
            $item['social'] = $fallback_defaults[$index] ?? 'fab fa-magento';
        }

        if (!empty($item['social'])) {
            $social = str_replace('fas fa-', '', $item['social']);
        }

        $link_key = 'link_' . $index;

        $widget->addRenderAttribute($link_key, 'href', $item['link']['url']);

        $className = str_replace('fab fa-', '', $social);
        $className = str_replace('fas fa-', '', $className);

        $widget->addRenderAttribute($link_key, 'class', [
            'gmt-icon',
            'gmt-social-icon',
            'gmt-social-icon-' . $className . $class_animation,
            'gmt-repeater-item-' . $item['_id'],
        ]);

        if ($item['link']['is_external']) {
            $widget->addRenderAttribute($link_key, 'target', '_blank');
        }

        if ($item['link']['nofollow']) {
            $widget->addRenderAttribute($link_key, 'rel', 'nofollow');
        } ?>
        <a <?= $widget->getRenderAttributeString($link_key); ?>>
            <span class="gmt-screen-only"><?= ucwords($social); ?></span>
            <?php Icons::renderIcon($item['social_icon']); ?>
        </a>
        <?php
    } ?>
</div>
