<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();
$tabs = $widget->getSettingsForDisplay('tabs_tabs');

$idInt = substr((string) $widget->getIdInt(), 0, 3); ?>
<div class="gmt-tabs" role="tablist">
    <div class="gmt-tabs-wrapper">
        <?php
        foreach ($tabs as $index => $item):
            $tabCount = $index + 1;
            $widget->addRenderAttribute('tab_title' . $index, [
                'id' => 'gmt-tab-title-' . $idInt . $tabCount,
                'class' => [ 'gmt-tab-title', 'gmt-tab-desktop-title' ],
                'data-tab' => $tabCount,
                'role' => 'tab',
                'aria-controls' => 'gmt-tab-content-' . $idInt . $tabCount,
            ]); ?>
            <div <?= /** @noEscape */ $widget->getRenderAttributeString('tab_title' . $index); ?>><a href=""><?= /** @noEscape */ $item['tabs_tab_title']; ?></a></div>
        <?php endforeach; ?>
    </div>
    <div class="gmt-tabs-content-wrapper">
        <?php
        foreach ($tabs as $index => $item):
            $tabCount = $index + 1;

            $tabContentSettingKey = 'tabs_tabs.' . $index . '.tabs_tab_content';
            $tabTitleMobileSettingKey = 'mobile.tabs_tabs.' . $index . '.tabs_tab_content';

            $widget->addRenderAttribute($tabContentSettingKey, [
                'id' => 'gmt-tab-content-' . $idInt . $tabCount,
                'class' => [ 'gmt-tab-content', 'gmt-clearfix' ],
                'data-tab' => $tabCount,
                'role' => 'tabpanel',
                'aria-labelledby' => 'gmt-tab-title-' . $idInt . $tabCount,
            ]);

            $widget->addRenderAttribute($tabTitleMobileSettingKey, [
                'class' => [ 'gmt-tab-title', 'gmt-tab-mobile-title' ],
                'data-tab' => $tabCount,
                'role' => 'tab',
            ]); ?>
            <div <?= /** @noEscape */ $widget->getRenderAttributeString($tabTitleMobileSettingKey); ?>><?= /** @noEscape */ $item['tabs_tab_title']; ?></div>
            <div <?= /** @noEscape */ $widget->getRenderAttributeString($tabContentSettingKey); ?>>
                <?php $widget->printInlineEditingContent($tabContentSettingKey, 'advanced'); ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
