<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Widgets\Text;

/**
 * @var Widget $block
 */
/** @var Text $widget */
$widget = $block->getWidget();

$settings = $block->getSettingsForDisplay();

$title = /** @noEscape */ trim((string) $settings['text_title']);

if ('' === $title) {
    return;
}

$widget->addRenderAttribute('title', 'class', 'gmt-text-title');

if (!empty($settings['text_size'])) {
    $widget->addRenderAttribute('title', 'class', 'gmt-size-' . $settings['text_size']);
}

if (!empty($settings['text_link']['url'])) {
    $widget->addRenderAttribute('url', 'href', $settings['text_link']['url']);

    if ($settings['text_link']['is_external']) {
        $widget->addRenderAttribute('url', 'target', '_blank');
    }

    if (!empty($settings['text_link']['nofollow'])) {
        $widget->addRenderAttribute('url', 'rel', 'nofollow');
    }
}
?>
<<?=  /** @noEscape */ $settings['text_tag'] ?> <?= /** @noEscape */ $widget->getRenderAttributeString('title') ?>>
    <?php if (!empty($settings['text_link']['url'])): ?>
        <a <?= /** @noEscape */ $widget->getRenderAttributeString('url') ?>>
    <?php endif; ?>
        <?php $widget->printInlineEditingContent('text_title'); ?>
    <?php if (!empty($settings['text_link']['url'])): ?>
        </a>
    <?php endif; ?>
</<?=  /** @noEscape */ $settings['text_tag'] ?>>
