<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */
declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Managers\Icons;
use Goomento\PageBuilder\Helper\EscaperHelper;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();
$settings = $block->getSettingsForDisplay();

$idInt = substr((string) $block->getIdInt(), 0, 3);

$hasIcon = !empty($settings['selected_icon']['value']); ?>
<div class="gmt-toggle" role="tablist">
    <?php
    foreach ($settings['tabs'] as $index => $item) :
    $tabCount = $index + 1;

    $tabTitleSettingKey = 'tabs.' . $index . '.tab_title';
    $tabContentSettingKey = 'tabs.' . $index . '.tab_content';

    $widget->addRenderAttribute($tabTitleSettingKey, [
        'id' => 'gmt-tab-title-' . $idInt . $tabCount,
        'class' => [ 'gmt-tab-title' ],
        'data-tab' => $tabCount,
        'role' => 'tab',
        'aria-controls' => 'gmt-tab-content-' . $idInt . $tabCount,
    ]);

    $widget->addRenderAttribute($tabContentSettingKey, [
        'id' => 'gmt-tab-content-' . $idInt . $tabCount,
        'class' => [ 'gmt-tab-content', 'gmt-clearfix' ],
        'data-tab' => $tabCount,
        'role' => 'tabpanel',
        'aria-labelledby' => 'gmt-tab-title-' . $idInt . $tabCount,
    ]);

    $widget->addInlineEditingAttributes($tabContentSettingKey, 'advanced'); ?>
    <div class="gmt-toggle-item">
        <<?= EscaperHelper::escapeHtml($settings['title_html_tag']); ?>
        <?= $widget->getRenderAttributeString($tabTitleSettingKey); ?>>
        <?php if ($hasIcon) : ?>
            <span class="gmt-toggle-icon gmt-toggle-icon-<?= EscaperHelper::escapeHtml($settings['icon_align']); ?>" aria-hidden="true">
                <span class="gmt-toggle-icon-closed"><?php Icons::renderIcon($settings['selected_icon']); ?></span>
                <span class="gmt-toggle-icon-opened"><?php Icons::renderIcon($settings['selected_active_icon'], [ 'class' => 'gmt-toggle-icon-opened' ]); ?></span>
            </span>
        <?php endif; ?>
        <a href=""><?= /** @noEscape */ $item['tab_title']; ?></a>
        </<?= EscaperHelper::escapeHtml($settings['title_html_tag']); ?>>
        <div <?= $widget->getRenderAttributeString($tabContentSettingKey); ?>><?= /** @noEscape */ $item['tab_content']; ?></div>
    </div>
<?php endforeach; ?>
</div>
