<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */
declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Managers\Icons;
use Goomento\PageBuilder\Helper\EscaperHelper;

/**
 * @var Widget $block
 */
$widget = $block->getWidget();
$settings = $block->getSettingsForDisplay();

$id_int = substr((string) $block->getIdInt(), 0, 3);

$has_icon = !empty($settings['selected_icon']['value']); ?>
<div class="gmt-toggle" role="tablist">
    <?php
    foreach ($settings['tabs'] as $index => $item) :
    $tab_count = $index + 1;

    $tab_title_setting_key = $widget->getRepeaterSettingKey('tab_title', 'tabs', $index);

    $tab_content_setting_key = $widget->getRepeaterSettingKey('tab_content', 'tabs', $index);

    $widget->addRenderAttribute($tab_title_setting_key, [
        'id' => 'gmt-tab-title-' . $id_int . $tab_count,
        'class' => [ 'gmt-tab-title' ],
        'data-tab' => $tab_count,
        'role' => 'tab',
        'aria-controls' => 'gmt-tab-content-' . $id_int . $tab_count,
    ]);

    $widget->addRenderAttribute($tab_content_setting_key, [
        'id' => 'gmt-tab-content-' . $id_int . $tab_count,
        'class' => [ 'gmt-tab-content', 'gmt-clearfix' ],
        'data-tab' => $tab_count,
        'role' => 'tabpanel',
        'aria-labelledby' => 'gmt-tab-title-' . $id_int . $tab_count,
    ]);

    $widget->addInlineEditingAttributes($tab_content_setting_key, 'advanced'); ?>
    <div class="gmt-toggle-item">
        <<?= EscaperHelper::escapeHtml($settings['title_html_tag']); ?>
        <?= $widget->getRenderAttributeString($tab_title_setting_key); ?>>
        <?php if ($has_icon) : ?>
            <span class="gmt-toggle-icon gmt-toggle-icon-<?= EscaperHelper::escapeHtml($settings['icon_align']); ?>" aria-hidden="true">
								<span class="gmt-toggle-icon-closed"><?php Icons::renderIcon($settings['selected_icon']); ?></span>
								<span class="gmt-toggle-icon-opened"><?php Icons::renderIcon($settings['selected_active_icon'], [ 'class' => 'gmt-toggle-icon-opened' ]); ?></span>
						</span>
        <?php endif; ?>
        <a href=""><?= $item['tab_title']; ?></a>
    </<?= EscaperHelper::escapeHtml($settings['title_html_tag']); ?>>
        <div <?= $widget->getRenderAttributeString($tab_content_setting_key); ?>><?= /** @noEscape */ $item['tab_content']; ?></div>
    </div>
<?php endforeach; ?>
</div>
