<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Block\View\Element\Widget;
use Goomento\PageBuilder\Builder\Controls\Groups\ImageSizeGroup;
use Goomento\PageBuilder\Helper\DataHelper;
use Goomento\PageBuilder\Helper\Embed;
use Goomento\PageBuilder\Builder\Widgets\Video;

/**
 * @var Widget $block
 */
/** @var Video $widget */
$widget = $block->getWidget();
$settings = $widget->getSettingsForDisplay();

$videoUrl = $settings[ implode('_', [Video::NAME, $settings['video_type'],  'url']) ] ?? '';

if ('other' === $settings['video_type']) {
    $videoUrl = $widget->getExternalVideoUrl();
}

if (empty($videoUrl)) {
    return;
}

if ('other' === $settings['video_type']) {
    $videoHtml = $widget->renderExternalVideo();
} else {
    $embedParams = $widget->getEmbedParams();
    $embedOptions = $widget->getEmbedOptions();
    $videoHtml = Embed::getEmbedHtml($videoUrl, $embedParams, $embedOptions);
}

if (empty($videoHtml)) {
    echo /** @noEscape */ $videoUrl;

    return;
}

$widget->addRenderAttribute('video-wrapper', 'class', 'gmt-wrapper');

if (!$settings['video_lightbox']) {
    $widget->addRenderAttribute('video-wrapper', 'class', 'gmt-fit-aspect-ratio');
}

$widget->addRenderAttribute('video-wrapper', 'class', 'gmt-open-' . ($settings['video_lightbox'] ? 'lightbox' : 'inline')); ?>
<div <?= /** @noEscape */ $widget->getRenderAttributeString('video-wrapper'); ?>>
    <?php
    if (!$settings['video_lightbox']) {
        echo /** @noEscape */ $videoHtml; // XSS ok.
    }

    if ($widget->hasImageOverlay()):
        $widget->addRenderAttribute('image-overlay', 'class', 'gmt-custom-embed-image-overlay');

        if ($settings['video_lightbox']) {
            if ('other' === $settings['video_type']) {
                $lightboxUrl = $videoUrl;
            } else {
                $lightboxUrl = Embed::getEmbedUrl($videoUrl, $embedParams, $embedOptions);
            }

            $lightboxOptions = [
                'type' => 'video',
                'videoType' => $settings['video_type'],
                'url' => $lightboxUrl,
                'modalOptions' => [
                    'id' => 'gmt-lightbox-' . $widget->getId(),
                    'entranceAnimation' => $settings['video_lightbox_content_animation'],
                    'entranceAnimation_tablet' => $settings['video_lightbox_content_animation_tablet'],
                    'entranceAnimation_mobile' => $settings['video_lightbox_content_animation_mobile'],
                    'videoAspectRatio' => $settings['video_aspect_ratio'],
                ],
            ];

            if ('other' === $settings['video_type']) {
                $lightboxOptions['videoParams'] = $widget->getExternalParams();
            }

            $widget->addRenderAttribute('image-overlay', [
                'data-gmt-open-lightbox' => 'yes',
                'data-gmt-lightbox' => DataHelper::encode($lightboxOptions),
            ]);

        } else {
            $widget->addRenderAttribute('image-overlay', 'style', 'background-image: url(' . $settings['video_image_overlay']['url'] ?? '' . ');');
        } ?>
        <div <?= /** @noEscape */ $widget->getRenderAttributeString('image-overlay'); ?>>
            <?php if ($settings['video_lightbox']): ?>
                <?= /** @noEscape */ ImageSizeGroup::getAttachmentImageHtml($settings, 'video_image_overlay'); ?>
            <?php endif; ?>
            <?php if ('yes' === $settings['video_show_play_icon']): ?>
                <div class="gmt-custom-embed-play" role="button">
                    <i class="far fa-play-circle"></i>
                    <span class="gmt-screen-only"><?= $block->escapeHtml(__('Play Video')); ?></span>
                </div>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>
