<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);
?>

<script type="text/template" id="tmpl-gmt-empty-preview">
	<div class="gmt-first-add">
		<div class="gmt-icon fa fa-plus"></div>
	</div>
</script>

<script type="text/template" id="tmpl-gmt-preview">
	<div class="gmt-section-wrap"></div>
</script>

<script type="text/template" id="tmpl-gmt-add-section">
	<div class="gmt-add-section-inner">
		<div class="gmt-add-section-close">
			<i class="fas fa-times" aria-hidden="true"></i>
			<span class="gmt-screen-only"><?= __( 'Close' ); ?></span>
		</div>
		<div class="gmt-add-new-section">
			<div class="gmt-add-section-area-button gmt-add-section-button" title="<?= __( 'Add New Section' ); ?>">
				<i class="fas fa-plus"></i>
			</div>
			<div class="gmt-add-section-area-button gmt-add-template-button" title="<?= __( 'Add Template' ); ?>">
				<i class="fas fa-folder"></i>
			</div>
			<div class="gmt-add-section-drag-title"><?= __( 'Drag widget here' ); ?></div>
		</div>
		<div class="gmt-select-preset">
			<div class="gmt-select-preset-title"><?= __( 'Select your Structure' ); ?></div>
			<ul class="gmt-select-preset-list">
				<#
					var structures = [ 10, 20, 30, 40, 21, 22, 31, 32, 33, 50, 60, 34 ];

					_.each( structures, function( structure ) {
					var preset = goomento.presetsFactory.getPresetByStructure( structure ); #>

					<li class="gmt-preset gmt-column gmt-col-16" data-structure="{{ structure }}">
						{{{ goomento.presetsFactory.getPresetSVG( preset.preset ).outerHTML }}}
					</li>
					<# } ); #>
			</ul>
		</div>
	</div>
</script>

<script type="text/template" id="tmpl-gmt-tag-controls-stack-empty">
	<?= __( 'This tag has no settings.' ); ?>
</script>
