<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

use Goomento\PageBuilder\Builder\Controls\Groups\TypographyGroup;
use Goomento\PageBuilder\Builder\Fonts;
use Goomento\PageBuilder\Builder\Managers\Controls;
use Goomento\PageBuilder\Configuration;
use Goomento\PageBuilder\Helper\EscaperHelper;
use Goomento\PageBuilder\Helper\ObjectManagerHelper;

?>
<script type="text/template" id="tmpl-gmt-panel">
	<div id="gmt-mode-switcher"></div>
	<header id="gmt-panel-header-wrapper"></header>
	<main id="gmt-panel-content-wrapper"></main>
	<footer id="gmt-panel-footer">
		<div class="gmt-panel-container">
		</div>
	</footer>
</script>

<script type="text/template" id="tmpl-gmt-panel-menu">
	<div id="gmt-panel-page-menu-content"></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-menu-group">
	<div class="gmt-panel-menu-group-title">{{{ title }}}</div>
	<div class="gmt-panel-menu-items"></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-menu-item">
	<div class="gmt-panel-menu-item-icon">
		<i class="{{ icon }}"></i>
	</div>
	<# if ( 'undefined' === typeof type || 'link' !== type ) { #>
		<div class="gmt-panel-menu-item-title">{{{ title }}}</div>
	<# } else {
		let target = ( 'undefined' !== typeof newTab && newTab ) ? '_blank' : '_self';
	#>
		<a href="{{ link }}" target="{{ target }}"><div class="gmt-panel-menu-item-title">{{{ title }}}</div></a>
	<# } #>
</script>

<script type="text/template" id="tmpl-gmt-panel-header">
	<div id="gmt-panel-header-menu-button" class="gmt-header-button">
		<i class="gmt-icon fa fa-bars tooltip-target" aria-hidden="true" data-tooltip="<?= __('Menu'); ?>"></i>
		<span class="gmt-screen-only"><?= __( 'Menu' ); ?></span>
	</div>
	<div id="gmt-panel-header-title"></div>
	<div id="gmt-panel-header-add-button" class="gmt-header-button">
		<i class="gmt-icon goomento-logo-white tooltip-target" aria-hidden="true" data-tooltip="<?= __('Widgets Panel'); ?>"></i>
		<span class="gmt-screen-only"><?= __( 'Widgets Panel' ); ?></span>
	</div>
</script>

<script type="text/template" id="tmpl-gmt-panel-footer-content">
	<div id="gmt-panel-footer-settings" class="gmt-panel-footer-tool gmt-leave-open tooltip-target" data-tooltip="<?= __('Settings'); ?>">
		<i class="fas fa-cog" aria-hidden="true"></i>
		<span class="gmt-screen-only"><?= ('%s Settings'); ?></span>
	</div>
	<div id="gmt-panel-footer-navigator" class="gmt-panel-footer-tool tooltip-target" data-tooltip="<?= __('Navigator') ?>">
		<i class="fas fa-location-arrow" aria-hidden="true"></i>
		<span class="gmt-screen-only"><?= __( 'Navigator' ); ?></span>
	</div>
	<div id="gmt-panel-footer-history" class="gmt-panel-footer-tool gmt-leave-open tooltip-target" data-tooltip="<?= __('History'); ?>">
		<i class="fas fa-history" aria-hidden="true"></i>
		<span class="gmt-screen-only"><?= __( 'History' ); ?></span>
	</div>
	<div id="gmt-panel-footer-responsive" class="gmt-panel-footer-tool gmt-toggle-state">
		<i class="fas fa-desktop tooltip-target" aria-hidden="true" data-tooltip="<?= __('Responsive Mode'); ?>"></i>
		<span class="gmt-screen-only">
			<?= __( 'Responsive Mode' ); ?>
		</span>
		<div class="gmt-panel-footer-sub-menu-wrapper">
			<div class="gmt-panel-footer-sub-menu">
				<div class="gmt-panel-footer-sub-menu-item" data-device-mode="desktop">
					<i class="gmt-icon fa fa-desktop" aria-hidden="true"></i>
					<span class="gmt-title"><?= __( 'Desktop' ); ?></span>
					<span class="gmt-description"><?= __( 'Default Preview' ); ?></span>
				</div>
				<div class="gmt-panel-footer-sub-menu-item" data-device-mode="tablet">
					<i class="gmt-icon fa fa-tablet" aria-hidden="true"></i>
					<span class="gmt-title"><?= __( 'Tablet' ); ?></span>
					<?php $breakpoints = Configuration::DEFAULT_BREAKPOINTS ?>
					<span class="gmt-description"><?= __( 'Preview for %1', $breakpoints['md'] . 'px'); ?></span>
				</div>
				<div class="gmt-panel-footer-sub-menu-item" data-device-mode="mobile">
					<i class="gmt-icon fa fa-mobile" aria-hidden="true"></i>
					<span class="gmt-title"><?= __( 'Mobile' ); ?></span>
					<span class="gmt-description"><?= __( 'Preview for %1', '360px'); ?></span>
				</div>
			</div>
		</div>
	</div>
	<div id="gmt-panel-footer-saver-preview" class="gmt-panel-footer-tool tooltip-target" data-tooltip="<?= __('Preview Changes'); ?>">
		<span id="gmt-panel-footer-saver-preview-label">
			<i class="fas fa-eye" aria-hidden="true"></i>
			<span class="gmt-screen-only"><?= __( 'Preview Changes' ); ?></span>
		</span>
	</div>
	<div id="gmt-panel-footer-saver-publish" class="gmt-panel-footer-tool">
		<button id="gmt-panel-saver-button-publish" class="gmt-button gmt-button-success gmt-disabled">
			<span class="gmt-state-icon">
				<i class="fa-circle-notch fas spinning" aria-hidden="true"></i>
			</span>
			<span id="gmt-panel-saver-button-publish-label">
				<?= __( 'Publish' ); ?>
			</span>
		</button>
	</div>
	<div id="gmt-panel-footer-saver-options" class="gmt-panel-footer-tool gmt-toggle-state">
		<button id="gmt-panel-saver-button-save-options" class="gmt-button gmt-button-success tooltip-target gmt-disabled" data-tooltip="<?= __('Save Options'); ?>">
			<i class="fas fa-caret-up" aria-hidden="true"></i>
			<span class="gmt-screen-only"><?= __( 'Save Options' ); ?></span>
		</button>
		<div class="gmt-panel-footer-sub-menu-wrapper">
			<p class="gmt-last-edited-wrapper">
				<span class="gmt-state-icon">
					<i class="fa-circle-notch fas spinning" aria-hidden="true"></i>
				</span>
				<span class="gmt-last-edited">
					{{{ goomento.config.document.last_edited }}}
				</span>
			</p>
			<div class="gmt-panel-footer-sub-menu">
				<div id="gmt-panel-footer-sub-menu-item-save-template" class="gmt-panel-footer-sub-menu-item">
					<i class="gmt-icon fa fa-folder" aria-hidden="true"></i>
					<span class="gmt-title"><?= __( 'Save as Template' ); ?></span>
				</div>
			</div>
		</div>
	</div>
</script>

<script type="text/template" id="tmpl-gmt-mode-switcher-content">
	<input id="gmt-mode-switcher-preview-input" type="checkbox">
	<label for="gmt-mode-switcher-preview-input" id="gmt-mode-switcher-preview">
		<i class="gmt-icon" aria-hidden="true" title="<?= __('Hide Panel'); ?>"></i>
		<span class="gmt-screen-only"><?= __( 'Hide Panel' ); ?></span>
	</label>
</script>

<script type="text/template" id="tmpl-editor-content">
	<div class="gmt-panel-navigation">
		<# _.each( elementData.tabs_controls, function( tabTitle, tabSlug ) {
			if ( 'content' !== tabSlug && ! goomento.userCan( 'save' ) ) {
				return;
			}
			$e.bc.ensureTab( 'panel/editor', tabSlug );
			#>
			<div class="gmt-component-tab gmt-panel-navigation-tab gmt-tab-control-{{ tabSlug }}" data-tab="{{ tabSlug }}">
				<a href="#">{{{ tabTitle }}}</a>
			</div>
		<# } ); #>
	</div>
	<# if ( elementData.reload_preview ) { #>
		<div class="gmt-update-preview">
			<div class="gmt-update-preview-title"><?= __( 'Update changes to page' ); ?></div>
			<div class="gmt-update-preview-button-wrapper">
				<button class="gmt-update-preview-button gmt-button gmt-button-success"><?= __( 'Apply' ); ?></button>
			</div>
		</div>
	<# } #>
	<div id="gmt-controls"></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-schemes-disabled">
	<i class="gmt-nerd-box-icon fas fa-glasses" aria-hidden="true"></i>
	<div class="gmt-nerd-box-title">{{{ '<?= __( "%s are disabled" ); ?>'.replace( '%s', disabledTitle ) }}}</div>
	<div class="gmt-nerd-box-message">You can enable it from the <a href="%s" target="_blank">Goomento settings page.</a></div>
</script>

<script type="text/template" id="tmpl-gmt-panel-scheme-color-item">
	<div class="gmt-panel-scheme-color-input-wrapper">
		<input type="text" class="gmt-panel-scheme-color-value" value="{{ value }}" data-alpha="true" />
	</div>
	<div class="gmt-panel-scheme-color-title">{{{ title }}}</div>
</script>

<script type="text/template" id="tmpl-gmt-panel-scheme-typography-item">
	<div class="gmt-panel-heading">
		<div class="gmt-panel-heading-toggle">
			<i class="gmt-icon" aria-hidden="true"></i>
		</div>
		<div class="gmt-panel-heading-title">{{{ title }}}</div>
	</div>
	<div class="gmt-panel-scheme-typography-items gmt-panel-box-content">
		<?php
		$scheme_fields_keys = TypographyGroup::getSchemeFieldsKeys();

		$typography_group = ObjectManagerHelper::get(Controls::class)->getControlGroups( 'typography' );
		$typography_fields = $typography_group->getFields();

		$scheme_fields = array_intersect_key( $typography_fields, array_flip( $scheme_fields_keys ) );

		foreach ( $scheme_fields as $option_name => $option ) :
			?>
			<div class="gmt-panel-scheme-typography-item">
				<div class="gmt-panel-scheme-item-title gmt-control-title"><?= $option['label']; ?></div>
				<div class="gmt-panel-scheme-typography-item-value">
					<?php if ( 'select' === $option['type'] ) : ?>
						<select name="<?= EscaperHelper::escapeHtml($option_name); ?>" class="gmt-panel-scheme-typography-item-field">
							<?php foreach ( $option['options'] as $field_key => $field_value ) : ?>
								<option value="<?= EscaperHelper::escapeHtml($field_key); ?>"><?= $field_value; ?></option>
							<?php endforeach; ?>
						</select>
					<?php elseif ( 'font' === $option['type'] ) : ?>
						<select name="<?= EscaperHelper::escapeHtml($option_name); ?>" class="gmt-panel-scheme-typography-item-field">
							<option value=""><?= __( 'Default' ); ?></option>
							<?php foreach ( Fonts::getFontGroups() as $group_type => $group_label ) : ?>
								<optgroup label="<?= EscaperHelper::escapeHtml($group_label); ?>">
									<?php foreach ( Fonts::getFontsByGroups( [ $group_type ] ) as $font_title => $font_type ) : ?>
										<option value="<?= EscaperHelper::escapeHtml($font_title); ?>"><?= $font_title; ?></option>
									<?php endforeach; ?>
								</optgroup>
							<?php endforeach; ?>
						</select>
					<?php elseif ( 'text' === $option['type'] ) : ?>
						<input name="<?= EscaperHelper::escapeHtml($option_name); ?>" class="gmt-panel-scheme-typography-item-field" />
					<?php endif; ?>
				</div>
			</div>
		<?php endforeach; ?>
	</div>
</script>

<script type="text/template" id="tmpl-gmt-control-responsive-switchers">
	<div class="gmt-control-responsive-switchers">
		<#
			var devices = responsive.devices || [ 'desktop', 'tablet', 'mobile' ];

			_.each( devices, function( device ) { #>
				<a class="gmt-responsive-switcher gmt-responsive-switcher-{{ device }}" data-device="{{ device }}">
					<i class="fas fa-{{ device }}"></i>
				</a>
			<# } );
		#>
	</div>
</script>

<script type="text/template" id="tmpl-gmt-control-dynamic-switcher">
	<div class="gmt-control-dynamic-switcher-wrapper">
		<div class="gmt-control-dynamic-switcher">
            <i class="far fa-plus-square"></i>
		</div>
	</div>
</script>

<script type="text/template" id="tmpl-gmt-control-dynamic-cover">
	<div class="gmt-dynamic-cover__settings">
		<i class="fas fa-{{ hasSettings ? 'wrench' : 'database' }}"></i>
	</div>
	<div class="gmt-dynamic-cover__title" title="{{{ title + ' ' + content }}}">{{{ title + ' ' + content }}}</div>
	<# if ( isRemovable ) { #>
		<div class="gmt-dynamic-cover__remove">
			<i class="fas fa-times-circle"></i>
		</div>
	<# } #>
</script>
