<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

?>
<script type="text/template" id="tmpl-gmt-repeater-row">
	<div class="gmt-repeater-row-tools">
		<# if ( itemActions.drag_n_drop ) {  #>
			<div class="gmt-repeater-row-handle-sortable">
                <i class="fas fa-ellipsis-v"></i>
				<span class="gmt-screen-only"><?= __( 'Drag & Drop' ); ?></span>
			</div>
		<# } #>
		<div class="gmt-repeater-row-item-title"></div>
		<# if ( itemActions.duplicate ) {  #>
			<div class="gmt-repeater-row-tool gmt-repeater-tool-duplicate">
                <i class="far fa-copy"></i>
				<span class="gmt-screen-only"><?= __( 'Duplicate' ); ?></span>
			</div>
		<# }
		if ( itemActions.remove ) {  #>
			<div class="gmt-repeater-row-tool gmt-repeater-tool-remove">
				<i class="fas fa-times" aria-hidden="true"></i>
				<span class="gmt-screen-only"><?= __( 'Remove' ); ?></span>
			</div>
		<# } #>
	</div>
	<div class="gmt-repeater-row-controls"></div>
</script>

<script type="text/template" id="tmpl-gmt-nested-repeater-row">
	<div class="gmt-repeater-row-tools">
		<# if ( itemActions.drag_n_drop ) {  #>
			<div class="gmt-repeater-row-handle-sortable">
                <i class="fas fa-ellipsis-v"></i>
				<span class="gmt-screen-only"><?= __( 'Drag & Drop' ); ?></span>
			</div>
		<# } #>
		<div class="gmt-repeater-row-item-title"></div>
        <div class="gmt-repeater-tool-move-left">
            <i class="fas fa-caret-left"></i>
        </div>
        <div class="gmt-repeater-tool-move-right">
            <i class="fas fa-caret-right"></i>
        </div>
		<# if ( itemActions.duplicate ) {  #>
			<div class="gmt-repeater-row-tool gmt-repeater-tool-duplicate">
                <i class="far fa-copy"></i>
				<span class="gmt-screen-only"><?= __( 'Duplicate' ); ?></span>
			</div>
		<# }
		if ( itemActions.remove ) {  #>
			<div class="gmt-repeater-row-tool gmt-repeater-tool-remove">
				<i class="fas fa-times" aria-hidden="true"></i>
				<span class="gmt-screen-only"><?= __( 'Remove' ); ?></span>
			</div>
		<# } #>
	</div>
	<div class="gmt-repeater-row-controls"></div>
</script>
