<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);

/**
 * @var LiveEditor $block
 */

use Goomento\PageBuilder\Block\Adminhtml\LiveEditor;

?>
<div id="root">
    <div id="gmt-editor-wrapper">
        <div id="gmt-panel" class="gmt-panel"></div>
        <div id="gmt-preview">
            <div id="gmt-loading">
                <div class="gmt-loader-wrapper">
                    <i class="goomento-logo gmt-loader"></i>
                    <div class="gmt-loading-title"><?= __('Loading'); ?></div>
                </div>
            </div>
            <div id="gmt-preview-responsive-wrapper" class="gmt-device-desktop gmt-device-rotate-portrait">
                <div id="gmt-preview-loading">
                    <i class="fa-circle-notch fas spinning" aria-hidden="true"></i>
                </div>
            </div>
        </div>
        <div id="gmt-navigator"></div>
    </div>
    <?= $block->getChildHtml() ?>
</div>
