<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);
/**
 * @var MediaBucket $block
 */

use Goomento\PageBuilder\Block\Adminhtml\MediaBucket;
use Goomento\PageBuilder\Core\DocumentsManager;
use Goomento\PageBuilder\Helper\StaticObjectManager;
/** @var DocumentsManager $documentManager */
$documentManager = StaticObjectManager::get(DocumentsManager::class);
$document = $documentManager->getCurrent();
$storeIds = $document->getContentModel()->getStoreId();
if ($storeIds) {
    $storeId = implode(',', $storeIds);
} else {
    $storeId = '0';
}
?>
<div class="image-bucket" data-bind="scope: 'uploader'" style="height: 0;width: 0">
    <input type="hidden" id="image-bucket">
</div>
<script>
    var mediaUrl = "<?= $block->getMediaUrl() ?>";
</script>
<script type="text/x-magento-init">
{
    ".image-bucket": {
        "Magento_Ui/js/core/app": {
                "components": {
                        "image-bucket": {
                            "component": "Goomento_PageBuilder/js/media-bucket/uploader",
                            "mediaGallery":{
                            "openDialogUrl":"<?= $block->getUrl('cms/wysiwyg_images/index', ['_secure' => true]) ?>",
                            "initialOpenSubpath":"wysiwyg",
                            "storeId":"<?= $storeId ?>"
                    }
                }
            }
        }
    }
}
</script>
