<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);
/**
 * @var \Magento\Backend\Block\Template $block
 */
?>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        'use strict';

        window.mediaBucket = {
            mediaIframe: "<?= $block->escapeUrl($block->getUrl('pagebuilder/content/media')) ?>",
            $iframe: null,
            gmtMediaUploader: null,
            _isFrameOpened: false,
            /**
             * Init script
             */
            create: function() {
                this.$iframe = $('<iframe />', {
                    src: this.mediaIframe,
                    css: {
                        position: 'fixed',
                        top: 0,
                        bottom: 0,
                        height: '100%',
                        width: 0,
                        zIndex: 9999,
                        right: 0,
                    }
                });

                this.$iframe.on('load', () => {
                    let check = setInterval(() => {
                        if (mediaBucket.$iframe[0].contentWindow.gmtMediaUploader) {
                            this.gmtMediaUploader = mediaBucket.$iframe[0].contentWindow.gmtMediaUploader;
                            clearInterval(check);
                        }
                    }, 1000);
                });

                $('body').append(this.$iframe);

                $(document.body).on('click.add-media-button', '.insert-media', function () {
                    mediaBucket.onSelected(function () {
                        let image = mediaBucket.get();
                        if (!_.isEmpty(image) && tinymce) {
                            let html = '<img src=\'' + image.url + '\' alt=\'\' title=\'\' />';
                            tinymce.activeEditor.execCommand('mceInsertContent', false, html);
                        }
                    });
                    mediaBucket.openFrame();
                });
            },
            /**
             * Open frame
             */
            openFrame: function() {
                this._isFrameOpened = true;
                $('body').addClass('gmt-media-open');
                this.gmtMediaUploader.openFrame();
                this.$iframe.animate({
                    width:'100%'
                }, 100);
                setTimeout(() => {
                    this._isFrameOpened && this.closeFrame();
                }, 60000);
            },
            /**
             * Close frame
             */
            closeFrame: function() {
                this._isFrameOpened = false;
                $('body').removeClass('gmt-media-open');
                this.$iframe.animate({
                    width: 0
                }, 100);
            },
            /**
             * Get image
             * @returns {*}
             */
            get: function () {
                return this.gmtMediaUploader.get();
            },
            /**
             * Wait for media stop return the file
             * @param callback
             * @returns {Window.mediaBucket}
             */
            onSelected: function (callback) {
                this.gmtMediaUploader.onSelected(callback);
            },
        };

        mediaBucket.create();
    });
</script>
