<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);
/**
 * @var MediaUploader $block
 */

use Goomento\PageBuilder\Helper\DataHelper;
use Goomento\PageBuilder\Block\Adminhtml\Editor\MediaUploader;
use Goomento\PageBuilder\Helper\ObjectManagerHelper;
use Goomento\PageBuilder\Helper\RequestHelper;
use Goomento\PageBuilder\Helper\UrlBuilderHelper;
use Magento\Framework\UrlInterface;

$editor = ObjectManagerHelper::getEditor();
$document = $editor->getDocument();
$storeId = (int) RequestHelper::getParam('store', 0);
if (DataHelper::getCustomMediaUrl()) {
    $mediaUrl = DataHelper::getCustomMediaUrl();
} else {
    $mediaUrl = UrlBuilderHelper::getFrontendUrl('', [
        '_type' => UrlInterface::URL_TYPE_MEDIA,
        'store_id' => $storeId,
    ]);
}
?>
<div class="image-bucket" style="height: 0;width: 0">
    <input type="hidden" id="image_bucket">
</div>
<script>
    window.goomentoMediaUrl = "<?=  /** @noEscape */ $mediaUrl ?>";
</script>
<script type="text/x-magento-init">
{
    ".image-bucket": {
        "Magento_Ui/js/core/app": {
                "components": {
                        "image-uploader": {
                            "component": "Goomento_PageBuilder/js/media/uploader",
                            "openDialogUrl": "<?= $block->escapeUrl($block->getMediaUploadUrl('image_bucket', (int) $storeId)) ?>",
                            "htmlId": "image_bucket"
                        }
                }
        }
    }
}
</script>
