<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);
/**
 * @var Template $block
 */

use Goomento\PageBuilder\Api\Data\SampleImportInterface;
use Goomento\PageBuilder\Helper\ObjectManagerHelper;
use Goomento\PageBuilder\Helper\RegistryHelper;
use Goomento\PageBuilder\Model\SampleImporterProcessor;
use Magento\Backend\Block\Template;

/** @var SampleImportInterface[] $allSamples */
$allSamples = (array) RegistryHelper::registry('all_import_samples');

/** @var SampleImporterProcessor $importProcessor */
$importProcessor = ObjectManagerHelper::get(
    SampleImporterProcessor::class
);
?>
<div class="admin__data-grid-wrap">
    <table class="data-grid">
        <thead>
            <tr>
                <th class="data-grid-th" align="center"><?= __('Name') ?></th>
                <th class="data-grid-th" align="center"><?= __('Templates') ?></th>
                <th class="data-grid-th" align="center"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php if (!empty($allSamples)) : ?>
            <?php foreach ($allSamples as $sampleName => $sample) : ?>
                <tr data-role="row">
                    <td>
                        <p><?= $block->escapeHtml($sample->getName()) ?></p>
                        <small><i><?= $block->escapeHtml($sample->getDescription()) ?></i></small>
                    </td>
                    <td style="padding: 0">
                        <?php if ($sources = (array) $importProcessor->setSourceDir($sample->getSourceFiles())->getSourceFiles()) : ?>
                            <table class="data-grid">
                                <tbody>
                                <?php foreach ($sources as $sourceFile) :
                                    $fileName = basename($sourceFile);
                                    ?>
                                    <tr>
                                        <td><?= $fileName ?></td>
                                        <td>
                                            <a href="?sample=<?= $block->escapeHtmlAttr($sampleName) ?>&filename=<?= $block->escapeHtmlAttr($fileName) ?>&import=1"><?= __('Import') ?></a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php endif; ?>
                    </td>
                    <td align="center">
                        <a href="?sample=<?= $block->escapeHtmlAttr($sampleName) ?>&import=1"><?= __('Import All') ?></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else : ?>
            <tr align="center">
                <td colspan="3"><small><?= __('Empty') ?></small></td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
</div>
