<?php
/**
 * @package Goomento_PageBuilder
 * @link https://github.com/Goomento/PageBuilder
 */

declare(strict_types=1);
/**
 * @var $block \Goomento\PageBuilder\Block\Adminhtml\Manage\GlobalCss
 */

use Goomento\PageBuilder\Helper\StaticEscaper;
use Goomento\PageBuilder\Model\Config;
?>

<form action=""
      method="POST"
      id="custom_css_form">
    <?= $block->getChildHtml('formkey')?>
    <label for="custom_css" />
    <textarea style="display: none" name="custom_css" id="custom_css"><?= StaticEscaper::escapeHtml($block->getCustomCss()) ?></textarea>
    <div id="gmt-editor">
        <?= __('Loading ...') ?>
    </div>
    <br />
    <button type="submit"><?= __('Save and Refresh') ?></button>
</form>
<style>
    #gmt-editor.loaded {
        box-shadow: 2px 2px 5px 2px #e6e6e6;
        font-size: 15px;
        border-radius: 3px;
    }
</style>
<script>
    require([
        'jquery',
        'https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.5/ace.js',
        'https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.5/ext-language_tools.js',
        '!domReady'
    ], function ($) {
        let $customCss = $('#custom_css'),
            $editor = $('#gmt-editor'),
            editor,
            windowVariableExisted = function (name, callback) {
                if (window[name]) {
                    callback(window[name]);
                } else {
                    let check = setInterval(() => {
                        if (window[name]) {
                            clearInterval(check);
                            callback(window[name]);
                        }
                    }, 1000);
                }
            },
            loadEditor = function (ace) {
                editor = ace.edit( 'gmt-editor' );

                editor.setOptions( {
                    mode: 'ace/mode/css',
                    minLines: 10,
                    maxLines: Infinity,
                    showGutter: true,
                    useWorker: true,
                    enableBasicAutocompletion: true,
                    enableLiveAutocompletion: true,
                } );

                editor.getSession().setUseWrapMode( true );
                editor.getSession().setValue( $customCss.val() );

                editor.getSession().on('change', function() {
                    $customCss.val( editor.getSession().getValue() );
                });

                $editor.addClass('loaded');
            };
        windowVariableExisted('ace', loadEditor);
    });
</script>
